### ISSUE TITLE
[score]签到-样式3，导致CPU单核满载

### ISSUE THREAD

**Issue by vatebur** [FloatTech/ZeroBot-Plugin#1001]
现象：CPU单核满载，并且不释放
能力有限，只能定位到这，不知道咋解决。
附上相关信息：

[pprof.main.samples.cpu.005.pb.gz](https://github.com/user-attachments/files/17324030/pprof.main.samples.cpu.005.pb.gz)

![0eb295c0c3378f060ad5191bcd054615](https://github.com/user-attachments/assets/0a89c212-cde1-4441-83de-19eb7d48e177)

![77ccb91a69212eede6f7f4a9abc1dc43](https://github.com/user-attachments/assets/faabd1cb-7b24-4d65-8c0b-7cc9473c5fcf)

![a441a07d7c35a516159eb7d4af0b68b4](https://github.com/user-attachments/assets/296dccd2-625b-42c9-ae8b-d268ee1c0445)

![0984c96135453ae379a871a55c8ffc3d](https://github.com/user-attachments/assets/a23d1cd8-bba9-4bc8-ae10-b2ade6423d4f)

**Comment by fumiama** [comment]
@Jiang-Red 我记得之前好像提到过这个问题，应该先把图片缩小再取颜色，这样的话可以降低占用。
