### ISSUE TITLE
拟声鸟口齿不清

### ISSUE THREAD

**Issue by dky1996** [FloatTech/ZeroBot-Plugin#103]
拟声鸟TTS完之后口齿不清，大概率听不清在说什么，能否通过参数传一份音频自定义音源？

**Comment by fumiama** [comment]
@guohuiyuan

**Comment by guohuiyuan** [comment]
那去偷模型啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月13日(星期四) 中午1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 拟声鸟口齿不清 (Issue #103)





 
@guohuiyuan
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guohuiyuan** [comment]
> 拟声鸟TTS完之后口齿不清，大概率听不清在说什么，能否通过参数传一份音频自定义音源？

去网站，一个一个生成固定话语的音频😂

**Comment by guohuiyuan** [comment]
> 拟声鸟TTS完之后口齿不清，大概率听不清在说什么，能否通过参数传一份音频自定义音源？

这是模型不太好的原因，有好的模型会偷过来

**Comment by guohuiyuan** [comment]
> 拟声鸟TTS完之后口齿不清，大概率听不清在说什么，能否通过参数传一份音频自定义音源？

有模型可以偷发给我，滑稽

**Comment by guohuiyuan** [comment]
> 

有几个示例模型，我没用

**Comment by dky1996** [comment]
所以之前是大佬自己训练的模型吗？
我看[MockingBird](https://github.com/babysor/MockingBird/blob/main/README-CN.md)有说可以使用社区预先训练好的合成器
目录2.3

**Comment by guohuiyuan** [comment]
> 所以之前是大佬自己训练的模型吗？ 我看[MockingBird](https://github.com/babysor/MockingBird/blob/main/README-CN.md)有说可以使用社区预先训练好的合成器 目录2.3

对就是预训练的模型，应该还可以，现在用的模型是偷的别人的，我自己训练了个药水哥，不知道效果好不好
