### ISSUE TITLE
签到功能似乎无法使用

### ISSUE THREAD

**Issue by Stardust-minus** [FloatTech/ZeroBot-Plugin#104]
![image](https://user-images.githubusercontent.com/52093397/149439592-9f41fa18-1de5-46c2-9961-2ff9bf7662c0.png)
![ZXVG6U@4ZA9SE__4~Q@CUWP](https://user-images.githubusercontent.com/52093397/149439678-008b9b66-ae96-4170-aa5a-b2e3c1a402bb.png)
如图
但是偶尔又可以正常用，原因不明
![%3 WC%TNS _K~7MCKN@8H6M](https://user-images.githubusercontent.com/52093397/149439763-83a58ef2-5019-43fb-a8a5-4eee453bb5fd.png)

系统CentOS 7.9 go1.17.2

**Comment by Stardust-minus** [comment]
更换了 b676e00 版本
现在日志里可以看到输出图片了，但是貌似机器人发不出来图
用其他插件可以发出图来，基本排除屏蔽问题。
![H7RK$CU8FR0SCS(UANMD%Q0](https://user-images.githubusercontent.com/52093397/149453939-3987581b-e8e1-441a-88dd-f5452c8ba2f1.png)
![image](https://user-images.githubusercontent.com/52093397/149453974-d76e9a98-47e8-40b7-9fa2-2673c7f728df.png)

**Comment by fumiama** [comment]
你的 zbp 和 ws 对端是否位于同一个主机

**Comment by Stardust-minus** [comment]
是的。127.0.0.1:6700




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月14日(星期五) 中午1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 签到功能似乎无法使用 (Issue #104)





 
你的 zbp 和 ws 对端是否位于同一个主机
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fumiama** [comment]
看一下对端的输出

**Comment by Stardust-minus** [comment]
> 看一下对端的输出

![(CEN$ KKA$JT@YRK~0M QF](https://user-images.githubusercontent.com/52093397/149455565-33213db0-0fba-4cfa-aafa-e5593aa27a33.png)
![image](https://user-images.githubusercontent.com/52093397/149455577-c853129f-b1d1-4cf5-bc19-d8a9055f88fd.png)

**Comment by fumiama** [comment]
这个对端不支持 file:/// 的图片上传，请尝试更新其版本或改用 go-cqhttp
