### ISSUE TITLE
请问aireply插件如何自定义chatgpt接口地址呢

### ISSUE THREAD

**Issue by geming20** [FloatTech/ZeroBot-Plugin#1042]
求教大佬，小白自行搭建了一个代理接口，请问如何更改默认的官方接口地址呢。

**Comment by YumeMichi** [comment]
https://github.com/FloatTech/AnimeAPI/blob/main/aireply/chatgpt.go

**Comment by geming20** [comment]
感谢大佬，虽然不知道怎么用。。。研究研究

**Comment by geming20** [comment]
> https://github.com/FloatTech/AnimeAPI/blob/main/aireply/chatgpt.go

感谢大佬，虽然不知道怎么用。。。研究研究
