### ISSUE TITLE
gif插件的素材库不全

### ISSUE THREAD

**Issue by JHue58** [FloatTech/ZeroBot-Plugin#1044]
gif插件素材来自(https://gitea.seku.su/fumiama/ImageMaterials/src/branch/main)
大部分指令无法使用

**Comment by fumiama** [comment]
哪里有全的

**Comment by JHue58** [comment]
> 哪里有全的

那gif插件提供的指令是都无法使用了嘛

**Comment by fumiama** [comment]
这我真不知道，这个插件的图库本来是别人提供的，然后他把它放在gitcode上面，但是之前gitcode直接锁了一大堆仓库，限制只有登录账号才能看，然后我顺藤摸瓜找到他最早在github的仓库，做了个镜像。也许他之后又加了一些图，但是我这儿根本没有，你可以去找找。

**Comment by JHue58** [comment]
> 这我真不知道，这个插件的图库本来是别人提供的，然后他把它放在gitcode上面，但是之前gitcode直接锁了一大堆仓库，限制只有登录账号才能看，然后我顺藤摸瓜找到他最早在github的仓库，做了个镜像。也许他之后又加了一些图，但是我这儿根本没有，你可以去找找。

那个仓库好像三年没更新了，哎，那也没办法了
