### ISSUE TITLE
无法设置桑帛云 api key

### ISSUE THREAD

**Issue by EatHatsuneShallots** [FloatTech/ZeroBot-Plugin#1048]
在私聊发送 “设置桑帛云 api key xxx” 没有效果，只会 AI 回复
“设置 ChatGPT api key xxx” 同样没有效果
已确认发送者是超级管理员，怀疑是 Matcher 优先级问题

LLOneBot 版本：4.1.2

**Comment by xyy0411** [comment]
如果把设置和使用分成两个插件好像就可以了吧

**Comment by EatHatsuneShallots** [comment]
> 如果把设置和使用分成两个插件好像就可以了吧

这个我不清楚，但值得一试

**Comment by YumeMichi** [comment]
试了一下似乎是zero.OnlyPrivate的问题

**Comment by xyy0411** [comment]
> 试了一下似乎是zero.OnlyPrivate的问题

这个rule我记得是匹配私聊消息的

**Comment by YumeMichi** [comment]
> > 试了一下似乎是zero.OnlyPrivate的问题
> 
> 这个规则我记得是匹配私聊消息的

这个ruler我加上，群消息机器人无响应、私聊无响应。去掉，群消息有响应，私聊无响应。
