### ISSUE TITLE
单独引入某个插件 报错 sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by xiaoyi510** [FloatTech/ZeroBot-Plugin#1053]
![image](https://github.com/user-attachments/assets/070f2cec-5d9d-4f0a-beb8-213f42939fa0)

**Comment by fumiama** [comment]
看zbp的go.mod, 需要在你的项目应用相同的两个replace。

**Comment by xiaoyi510** [comment]
收到 原来是在go mod 里面的是加入到最后 而不是直接替换掉引用的数据 感谢
