### ISSUE TITLE
更新 zerobot 1.8.0 zerobot-plugin 1.8.4 后插件报错

### ISSUE THREAD

**Issue by xiaoyi510** [FloatTech/ZeroBot-Plugin#1063]
![image](https://github.com/user-attachments/assets/303615bb-84aa-4e6e-bbf5-8c11f938a7b7)

![Uploading image.png…]()

**Comment by xiaoyi510** [comment]
手动修改gomod 文件版本号解决 go get -u 无法获取新版本的样子

**Comment by fumiama** [comment]
直接拉最新版。
