### ISSUE TITLE
【bug】签到炸了

### ISSUE THREAD

**Issue by xyy0411** [FloatTech/ZeroBot-Plugin#1067]
![image](https://github.com/user-attachments/assets/24eb298d-c8da-4f6c-8748-a0f157714829)
如图

**Comment by vatebur** [comment]
第一次签到的时候，下载签到背景失败就会这样。
实际上已经签到成功了，但是没有生成签到图片
这俩天用于下载的服务器不稳定才会这样。

你应该把第一次签到时候的报错也一起截出来。
![f48c6c4bb6208936a7eeceb611a65bec](https://github.com/user-attachments/assets/8c7ea677-5e69-42d9-b592-caf906cafc57)

**Comment by vatebur** [comment]
#997

**Comment by xyy0411** [comment]
![IMG_20241125_120509.jpg](https://github.com/user-attachments/assets/58c043df-6b02-4c01-9a59-8c853e0e0733)

报错403
