### ISSUE TITLE
有关 plugin_music 的问题

### ISSUE THREAD

**Issue by xhemj** [FloatTech/ZeroBot-Plugin#116]
问题场景：任意发送`点歌 XXX`时机器人返回的音乐卡片无法直接在聊天界面点击播放键播放，而是要点进网页后才能播放。
稍微看了一下QQ音乐的部分，好像是
https://github.com/FloatTech/ZeroBot-Plugin/blob/a16bcda7dadb87085e3c0dc580a96451d07a3b42/plugin_music/selecter.go#L195
这里api返回的内容后没有把`\u0026`转成`&`再进行拼接。
自己手动替换后是可以正常播放的
（抱歉并不懂 Go 是怎么写的，所以只能来反馈一下）

**Comment by fumiama** [comment]
这边无法复现，请提供更详细的信息。另外\u0026是会被转换的，应该不是这里的问题。

**Comment by xhemj** [comment]
![](https://ae05.alicdn.com/kf/Hac8deec1d0314adf891e2265dd2f76bdj.png)
图中`audio`应该是音频的链接，但实际发送的却只有`https://isure.stream.qqmusic.qq.com/`

**Comment by Yiwen-Chan** [comment]
实测 `点歌好运来` 是正常的，估计是 api 的问题
