### ISSUE TITLE
在s390x架构上编译失败报错

### ISSUE THREAD

**Issue by dky1996** [FloatTech/ZeroBot-Plugin#118]
# 在s390x架构上编译失败报错

## 在windows10上交叉编译失败：
![image](https://user-images.githubusercontent.com/24567171/153339000-154faf90-0974-43ce-ba1d-3c78d5e30182.png)
```
C:\Users\go\pkg\mod\github.com\fumiama\go-base16384@v1.2.1\base14stub.go:6:16: cannot use "stub!" (type untyped string) as type byte in slice literal
C:\Users\go\pkg\mod\github.com\fumiama\go-base16384@v1.2.1\base14stub.go:10:16: cannot use "stub!" (type untyped string) as type byte in slice literal
C:\Users\go\pkg\mod\github.com\fumiama\go-base16384@v1.2.1\base14stub.go:14:16: cannot use "stub!" (type untyped string) as type byte in slice literal
C:\Users\go\pkg\mod\github.com\fumiama\go-base16384@v1.2.1\base14stub.go:18:16: cannot use "stub!" (type untyped string) as type byte in slice literal
```

## 在s390x架构的ubuntu上直接编译也失败：
![image](https://user-images.githubusercontent.com/24567171/153339184-989cd5e3-51ee-499e-9d79-0a1808043f76.png)
报错内容相同.

## 本小白试图处理并且失败
将github.com/fumiama/go-base16384模组replace到本地，花括号改成小括号之后报其他新错误：
![image](https://user-images.githubusercontent.com/24567171/153339792-1b3f22bf-869c-4b8d-aa61-0819933ac69d.png)

### ps：同样的代码在linux/amd64和windows/amd64都能正常编译

**Comment by fumiama** [comment]
s390x是罕见的架构，本项目有一些模块可能不支持。关于base16384的问题我可以修正，但是不保证其他包不报错。

**Comment by fumiama** [comment]
最新版本已修复，请再次尝试编译。

**Comment by fumiama** [comment]
语音消息需要安装`ffmpeg`

**Comment by dky1996** [comment]
哦哦！我的问题。
