### ISSUE TITLE
签到功能崩溃问题

### ISSUE THREAD

**Issue by SakuraAzusa** [FloatTech/ZeroBot-Plugin#122]
环境：Ubuntu 20.04 LTS
使用签到时占用会膨胀得很厉害（20M→200~400M内存占用）
由于服务器只有1h1r，服务器会直接满载
如果同时多人签到会高概率直接导致程序崩溃

time="2022-02-11T17:57:09+08:00" level=info msg="收到群(*********)消息 fk?↘ : 签到"

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:93)[0m 
[33m[2022-02-11 17:57:09][0m  [36;1m[1.05ms][0m  SELECT * FROM "sign_in"  WHERE (uid = 545813780 ) ORDER BY "sign_in"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:104)[0m 
[33m[2022-02-11 17:57:09][0m  [36;1m[0.45ms][0m  SELECT * FROM "sign_in"  WHERE "sign_in"."uid" = 545813780 AND ((uid = 545813780 )) ORDER BY "sign_in"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:110)[0m 
[33m[2022-02-11 17:57:09][0m  [36;1m[0.56ms][0m  UPDATE "sign_in" SET "count" = 0, "updated_at" = '2022-02-11 17:57:09'  WHERE (uid = 545813780 )  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:104)[0m 
[33m[2022-02-11 17:57:12][0m  [36;1m[1.28ms][0m  SELECT * FROM "sign_in"  WHERE "sign_in"."uid" = 545813780 AND ((uid = 545813780 )) ORDER BY "sign_in"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:110)[0m 
[33m[2022-02-11 17:57:12][0m  [36;1m[0.62ms][0m  UPDATE "sign_in" SET "count" = 6, "updated_at" = '2022-02-11 17:57:12'  WHERE (uid = 545813780 )  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:65)[0m 
[33m[2022-02-11 17:57:17][0m  [36;1m[32.33ms][0m  SELECT * FROM "score"  WHERE (uid = 545813780 ) ORDER BY "score"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:76)[0m 
[33m[2022-02-11 17:57:17][0m  [36;1m[0.85ms][0m  SELECT * FROM "score"  WHERE "score"."uid" = 545813780 AND ((uid = 545813780 )) ORDER BY "score"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:82)[0m 
[33m[2022-02-11 17:57:17][0m  [36;1m[2.59ms][0m  UPDATE "score" SET "score" = 6  WHERE (uid = 545813780 )  
[36;31m[1 rows affected or returned ][0m 
time="2022-02-11T17:57:26+08:00" level=info msg="发送群消息(*********): [{\"type\":\"image\",\"data\":{\"file\":\"file:////root/zero/data/score/cache/54581378020220211signin.png\"}}] (id=-1107387172)"
time="2022-02-11T17:57:45+08:00" level=info msg="收到群(*********)消息 空と翼 : 签到"

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:93)[0m 
[33m[2022-02-11 17:57:45][0m  [36;1m[2.01ms][0m  SELECT * FROM "sign_in"  WHERE (uid = 1281009466 ) ORDER BY "sign_in"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:104)[0m 
[33m[2022-02-11 17:57:45][0m  [36;1m[0.30ms][0m  SELECT * FROM "sign_in"  WHERE "sign_in"."uid" = 1281009466 AND ((uid = 1281009466 )) ORDER BY "sign_in"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:110)[0m 
[33m[2022-02-11 17:57:45][0m  [36;1m[2.02ms][0m  UPDATE "sign_in" SET "count" = 0, "updated_at" = '2022-02-11 17:57:45'  WHERE (uid = 1281009466 )  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:104)[0m 
[33m[2022-02-11 17:57:52][0m  [36;1m[0.82ms][0m  SELECT * FROM "sign_in"  WHERE "sign_in"."uid" = 1281009466 AND ((uid = 1281009466 )) ORDER BY "sign_in"."uid" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin_score/model.go:110)[0m 
[33m[2022-02-11 17:57:52][0m  [36;1m[73.22ms][0m  UPDATE "sign_in" SET "count" = 11, "updated_at" = '2022-02-11 17:57:52'  WHERE (uid = 1281009466 )  
[36;31m[1 rows affected or returned ][0m

**Comment by fumiama** [comment]
这是签到时的正常内存占用，因为签到制图所用头图分辨率较高。考虑将其限制在某个分辨率一下。

**Comment by fumiama** [comment]
已经将分辨率限制在`1280*720`以内，可以试试最新版。

**Comment by SakuraAzusa** [comment]
现在多人签到没问题了，十分感谢，我用一段时间看看
