### ISSUE TITLE
suggestion: 大家还是不要用oneBot_mirai了，1年没更了

### ISSUE THREAD

**Issue by FuYon** [FloatTech/ZeroBot-Plugin#127]
你好，受限于个人水平和理解能力，我在使用onebot mirai对ZeroBotPlugins进行连接的时候出现问题，抱歉占用几分钟的时间（元宵快乐 >w<）
## 日志：
**登陆后mirai报错：**
![image](https://user-images.githubusercontent.com/57851695/153980758-6dc0206c-87d1-48d9-98d1-56ffcec79f0e.png)
zbp还是老样子：
![image](https://user-images.githubusercontent.com/57851695/153981455-1dd622d4-c3f9-452d-aa7f-1b3223de9f4e.png)
## 配置文件
**我的onebot mirai插件配置：**
![image](https://user-images.githubusercontent.com/57851695/153981306-b5b2c575-6969-4b88-879c-1390f2774263.png)
**我的main.go配置：**
![image](https://user-images.githubusercontent.com/57851695/153981528-80d57e4b-a436-4c49-9faa-c51da64b4cc9.png)
**我的mirai api http配置（应该没用，但还是要放的）**
![image](https://user-images.githubusercontent.com/57851695/153981657-c3e06111-6f85-438d-bcb0-1ceb5cdd42aa.png)

哇塞，你居然看完了吗？谢谢你！

**Comment by FuYon** [comment]
在目前的版本，依照 #18 可以完美解决问题吗

**Comment by fumiama** [comment]
mirai不要用反向ws

**Comment by FuYon** [comment]
![image](https://user-images.githubusercontent.com/57851695/153995717-45609e82-b7d9-4269-81ce-d7ce2f4892ec.png)
然后成了这种情况，连接后马上断开（）

**Comment by FuYon** [comment]
![image](https://user-images.githubusercontent.com/57851695/153995800-1308b70b-e164-4356-8a16-7cbf1b5ebef5.png)
改成正向了，疯狂连接再断开（）

**Comment by FuYon** [comment]
我好了，谢谢

**Comment by fumiama** [comment]
是
