### ISSUE TITLE
[bug] vtb语录发送报错

### ISSUE THREAD

**Issue by dky1996** [FloatTech/ZeroBot-Plugin#128]
## vtb语录发送失败，cqhttp报错
系统是Debian系统 linux/amd64，有安装ffmpeg
![image](https://user-images.githubusercontent.com/24567171/154390645-05d254b7-46a9-4250-8d82-2cc0ccbd77a4.png)

![image](https://user-images.githubusercontent.com/24567171/154389100-cd01f792-571b-452c-b80c-7036626e22d7.png)
看报错应该是格式问题。

zerobot部分报错为：
![image](https://user-images.githubusercontent.com/24567171/154390418-4cbe9657-c553-40e3-8b13-1087f061c77c.png)
好像没什么参考价值。

直接get调用接口：
![image](https://user-images.githubusercontent.com/24567171/154391659-8761e2c4-2a85-414b-ac58-23c6acef8af1.png)
content-type是对的，不确定是否是accept的问题，看着像是cqhttp的问题。

**Comment by fumiama** [comment]
可能是服务器无法访问该网址，请在服务器上进行测试。

**Comment by dky1996** [comment]
curl之后回复是个html，
![image](https://user-images.githubusercontent.com/24567171/154404428-8302657c-0440-49fa-a19f-fb1d5b704ff3.png)
打开之后是：
![image](https://user-images.githubusercontent.com/24567171/154404464-5e0bddd7-4edd-4813-aeed-69878f74aee3.png)
看上去是被cf拦截了，导致下载不到音频

**Comment by Yiwen-Chan** [comment]
可以参考此处源码 https://github.com/FloatTech/AnimeAPI/blob/main/ascii2d/ascii2d.go#L26
```
transport := http.Transport{
		TLSClientConfig: &tls.Config{
			MaxVersion: tls.VersionTLS12,
		},
	}
	client := &http.Client{
		Transport: &transport,
	}
```

**Comment by Yiwen-Chan** [comment]
> 可以参考此处源码 https://github.com/FloatTech/AnimeAPI/blob/main/ascii2d/ascii2d.go#L26
> 
> ```
> transport := http.Transport{
> 		TLSClientConfig: &tls.Config{
> 			MaxVersion: tls.VersionTLS12,
> 		},
> 	}
> 	client := &http.Client{
> 		Transport: &transport,
> 	}
> ```

修改此段代码，在 `ZeroBot` 下载后再交给 `go-cqhttp` 处理

**Comment by guohuiyuan** [comment]
> > 可以参考此处源码 https://github.com/FloatTech/AnimeAPI/blob/main/ascii2d/ascii2d.go#L26
> > ```
> > transport := http.Transport{
> > 		TLSClientConfig: &tls.Config{
> > 			MaxVersion: tls.VersionTLS12,
> > 		},
> > 	}
> > 	client := &http.Client{
> > 		Transport: &transport,
> > 	}
> > ```
> 
> 修改此段代码，在 `ZeroBot` 下载后再交给 `go-cqhttp` 处理

好麻烦啊

**Comment by dky1996** [comment]
谢大佬~

**Comment by qwaszx123wjz** [comment]
我也遇到此问题，请问解决了吗，怎么解决的？

**Comment by dky1996** [comment]
> 我也遇到此问题，请问解决了吗，怎么解决的？

 更新bot到最新版本，作者已经解决了

**Comment by guohuiyuan** [comment]
为什么不放截图，或者自测一下网络。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 晚上11:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] [bug] vtb语录发送报错 (Issue #128)





 
我更新到最新版本后还是出现这个问题，请问楼主解决了吗，是不是要在哪里改代码才行？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qwaszx123wjz** [comment]
> 为什么不放截图，或者自测一下网络。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月21日(星期一) 晚上11:12 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [FloatTech/ZeroBot-Plugin] [bug] vtb语录发送报错 (Issue #128) 我更新到最新版本后还是出现这个问题，请问楼主解决了吗，是不是要在哪里改代码才行？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

不好意思，第一次提问。找到原因了，是没有安装ffmpeg
