### ISSUE TITLE
关键字搜图功能失效

### ISSUE THREAD

**Issue by zyh001** [FloatTech/ZeroBot-Plugin#139]
使用指令`来张xxx`，机器人错误输出
```text
ERROR: invalid character '<' looking for beginning of value (id=-xxxxxxxx) 
```

**Comment by zyh001** [comment]
> 因为对端加了cf验证码。你可以尝试修复该问题并pr。

我查看了位于`plugin/image_finder/keyword.go`的代码， 似乎是通过`https://api.pixivel.moe/v2/pixiv/illust/search/`的API进行搜索，那么获取到Pixiv的ID号后进行下载即可，应该不涉及验证码吧

**Comment by fumiama** [comment]
> > 因为对端加了cf验证码。你可以尝试修复该问题并pr。
> 
> 我查看了位于`plugin/image_finder/keyword.go`的代码， 似乎是通过`https://api.pixivel.moe/v2/pixiv/illust/search/`的API进行搜索，那么获取到Pixiv的ID号后进行下载即可，应该不涉及验证码吧

笔给你，你来写。

**Comment by fumiama** [comment]
前言撤回，找到方法了，请尝试最新版。
