### ISSUE TITLE
哔哩哔哩订阅无法使用

### ISSUE THREAD

**Issue by Myzhazha** [FloatTech/ZeroBot-Plugin#149]
哔哩哔哩订阅无法使用
![Screenshot_20220315-081741__01](https://user-images.githubusercontent.com/25764781/158281756-cae44507-99d1-4907-b2d6-ddb7a7ad7923.jpg)

**Comment by fumiama** [comment]
请提供详细日志信息

@guohuiyuan

**Comment by Myzhazha** [comment]
> 请提供详细的日志信息
> 
> @guohuiyuan

![Uploading Screenshot_20220316-074857.jpg…]()

**Comment by Myzhazha** [comment]
> 请提供详细的日志信息
> 
> @guohuiyuan
![Screenshot_20220316-074857](https://user-images.githubusercontent.com/25764781/158490735-83da9978-2b06-40f2-800f-ff75fa31a5cc.jpg)

**Comment by guohuiyuan** [comment]
> > 请提供详细的日志信息
> > @guohuiyuan
> > ![Screenshot_20220316-074857](https://user-images.githubusercontent.com/25764781/158490735-83da9978-2b06-40f2-800f-ff75fa31a5cc.jpg)

这是setutime和bilibilipush的正则冲突了吧

**Comment by guohuiyuan** [comment]
> > 请提供详细的日志信息
> > @guohuiyuan
> > ![Screenshot_20220316-074857](https://user-images.githubusercontent.com/25764781/158490735-83da9978-2b06-40f2-800f-ff75fa31a5cc.jpg)

正常是不会有少女祈祷中，因为它很快只是，改一下数据库而已

**Comment by Yiwen-Chan** [comment]
这是和setutime插件命令有冲突，修改一下优先级就可以了

**Comment by guohuiyuan** [comment]
后续我改一下正则吧。。
