### ISSUE TITLE
coser指令无法使用

### ISSUE THREAD

**Issue by mentlesoul** [FloatTech/ZeroBot-Plugin#150]
![image](https://user-images.githubusercontent.com/61239889/158741470-2f7e2baf-61d5-4a81-ab41-9bef02ea2861.png)
![image](https://user-images.githubusercontent.com/61239889/158741505-720ad61a-0171-4669-8e0d-b44e4f047009.png)
如图，coser指令不能使用
系统：win10
已经尝试重新下载zerobot，无效
ffmpeg设置过了

**Comment by fumiama** [comment]
请尝试最新action版 https://github.com/FloatTech/ZeroBot-Plugin/actions/runs/1987402968

**Comment by mentlesoul** [comment]
> 请尝试最新action版 https://github.com/FloatTech/ZeroBot-Plugin/actions/runs/1987402968

我直接下载源码，改完配置文件后，bat脚本运行的

**Comment by fumiama** [comment]
我看你的截图不是最新。报错一样吗

**Comment by mentlesoul** [comment]
> 我看你的截图不是最新。报错一样吗

寄，重新下载一遍，修改完配置文件
coser指令直接无反应了
![image](https://user-images.githubusercontent.com/61239889/158754083-e2123054-a58b-433c-b503-0a8a6cf68d55.png)
紫色那几行是订阅的b站用户动态

**Comment by fumiama** [comment]
看来是api有问题了 @guohuiyuan

**Comment by mentlesoul** [comment]
附
今天又试了一次，反馈是
[2022-03-18 15:53:24] [WARNING]: 警告: 非法 Forward node 将跳过. uin: 3144585698 name: 山河 content count: 0

**Comment by guohuiyuan** [comment]
> 看来是api有问题了 @guohuiyuan

![image](https://user-images.githubusercontent.com/54976075/158959632-b4794643-a553-48ec-940b-3a684bc0b9db.png)
api没挂

**Comment by guohuiyuan** [comment]
> 

估计是你的机器网络有问题

**Comment by guohuiyuan** [comment]
在机器上试一下
curl http://ovooa.com/API/cosplay/api.php

**Comment by mentlesoul** [comment]
connection refused
是不是要挂梯子？

**Comment by guohuiyuan** [comment]
> > 在机器上试一下
> > curl http://ovooa.com/API/cosplay/api.php
> 
> connection refused 是不是要挂梯子？

不需要梯子的，就是服务器的问题，可能你的服务器拒绝访问某些ip

**Comment by mentlesoul** [comment]
> > > 在机器上试一下
> > > curl http://ovooa.com/API/cosplay/api.php
> > 
> > 
> > connection refused 是不是要挂梯子？
> 
> 不需要梯子的，就是服务器的问题，可能你的服务器拒绝访问某些ip

怪了，我服务器就是一台台式机，放在家里的
昨天晚上挂了梯子倒是能用coser了但是延迟有15-20s左右，总不能一直挂着梯子吧

**Comment by fumiama** [comment]
建议换个api，这个api出图太多容易风控，而且图片不符合标题。我找到一个：https://api.iyk0.com/cos，不过不是成系列的，是一次一张。

**Comment by mentlesoul** [comment]
> 建议换个api，这个api出图太多容易风控，而且图片不符合标题。我找到一个：https://api.iyk0.com/cos ，不过不是成系列的，是一次一张。

这个插件对于使用的api有什么要求么，是要直接给图或者给出图链接的才行么
对了能否直接私聊（

**Comment by fumiama** [comment]
![屏幕快照 2022-03-19 上午11 24 55](https://user-images.githubusercontent.com/41315874/159104882-0352640f-fa54-4840-84d8-c11f3fd4911f.png)
@guohuiyuan 另外建议按这个url中的日期，只提取最前面的同一日的图以避免传太多。

**Comment by mentlesoul** [comment]
> ![屏幕快照 2022-03-19 上午11 24 55](https://user-images.githubusercontent.com/41315874/159104882-0352640f-fa54-4840-84d8-c11f3fd4911f.png) @guohuiyuan 另外建议按这个url中的日期，只提取最前面的同一日的图以避免传太多。

啊是的，图超过大概六七张就会有部分发送失败

**Comment by fumiama** [comment]
> > 建议换个api，这个api出图太多容易风控，而且图片不符合标题。我找到一个：https://api.iyk0.com/cos ，不过不是成系列的，是一次一张。
> 
> 这个插件对于使用的api有什么要求么，是要直接给图或者给出图链接的才行么 对了能否直接私聊（

想要私聊就只能一次发一张。

**Comment by mentlesoul** [comment]
> > > 建议换个api，这个api出图太多容易风控，而且图片不符合标题。我找到一个：https://api.iyk0.com/cos ，不过不是成系列的，是一次一张。
> > 
> > 
> > 这个插件对于使用的api有什么要求么，是要直接给图或者给出图链接的才行么 对了能否直接私聊（
> 
> 想要私聊就只能一次发一张。

噗，我说的是私聊询问api之类的，github写comment对于单个问题还好但是效率略低orz

**Comment by fumiama** [comment]
不同api返回的数据不一样，没法全部适配，因此没必要私聊。当然对于这个api访问不到的问题，我会考虑加一个代理。

**Comment by guohuiyuan** [comment]
> ![屏幕快照 2022-03-19 上午11 24 55](https://user-images.githubusercontent.com/41315874/159104882-0352640f-fa54-4840-84d8-c11f3fd4911f.png) @guohuiyuan 另外建议按这个url中的日期，只提取最前面的同一日的图以避免传太多。

按日期分组发？我想全都要😍

**Comment by mentlesoul** [comment]
> > ![屏幕快照 2022-03-19 上午11 24 55](https://user-images.githubusercontent.com/41315874/159104882-0352640f-fa54-4840-84d8-c11f3fd4911f.png) @guohuiyuan 另外建议按这个url中的日期，只提取最前面的同一日的图以避免传太多。
> 
> 按日期分组发？我想全都要😍

有的时候一天图特别多，有的时候特别少
我建议按五张或者七八张为一组发出来（x<=7/8)
