### ISSUE TITLE
获取图片时出错

### ISSUE THREAD

**Issue by mentlesoul** [FloatTech/ZeroBot-Plugin#151]
![9{7SHD 1AR)5$)X%_(%7J(N](https://user-images.githubusercontent.com/61239889/158757978-939edc21-7860-46e2-9206-1da8a0396868.png)
刚刚重新下载后，不断在群内发送这个消息

**Comment by fumiama** [comment]
哪个插件

**Comment by mentlesoul** [comment]
> 哪个插件

完全看不出来，每一条指令的图片都发出来了，然后过了几秒钟突然弹出了这个

**Comment by fumiama** [comment]
那你在此之前运行过哪些指令

**Comment by mentlesoul** [comment]
> 那你在此之前运行过哪些指令

![image](https://user-images.githubusercontent.com/61239889/158786520-03fdea1c-88cb-4d81-9236-afd05f12068a.png)
![image](https://user-images.githubusercontent.com/61239889/158786539-d9f41c51-958c-404f-93f5-e8994fd5471c.png)
![image](https://user-images.githubusercontent.com/61239889/158786563-0bb905ce-5f17-44a8-8464-99a8b209c361.png)
两次来份涩图，一次来份二次元
然后就是这个了

**Comment by mentlesoul** [comment]
> 那你在此之前运行过哪些指令

**Comment by mentlesoul** [comment]
> 那你在此之前运行过哪些指令

测试了一下，确定是setutime这个插件的问题

**Comment by fumiama** [comment]
应该是dns被污染了，你可以试试把8.8.8.8放进代理。

**Comment by mentlesoul** [comment]
> 应该是dns被污染了，你可以试试把8.8.8.8放进代理。

已解决
