### ISSUE TITLE
bilibili push报错导致崩溃

### ISSUE THREAD

**Issue by mentlesoul** [FloatTech/ZeroBot-Plugin#162]
[ERROR] [bilibilipush]: Post "https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids": read tcp 192.168.0.199:50217->164.52.28.62:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by fumiama** [comment]
@guohuiyuan

**Comment by guohuiyuan** [comment]
> @guohuiyuan

解决不了啊，net/http有时候抽风崩溃，以前做爬虫的时候用代理也是总是崩，最好不要用代理吧
