### ISSUE TITLE
定时指令触发器无法工作

### ISSUE THREAD

**Issue by zcwang666** [FloatTech/ZeroBot-Plugin#169]
系统win10，zerobot版本最新，在定时触发的时候机器人返回
![image](https://user-images.githubusercontent.com/69986837/159838812-8855783b-6c3c-403c-ab7f-b715c4bbb773.png)

**Comment by fumiama** [comment]
是直接用的最新版，还是修改后自己编译的？

**Comment by fumiama** [comment]
目前看来是mirai的问题，请尝试使用go-cqhttp

**Comment by zcwang666** [comment]
> 目前看来是mirai的问题，请尝试使用go-cqhttp

好的
