### ISSUE TITLE
今日早报变成昨日火星晚报了

### ISSUE THREAD

**Issue by dky1996** [FloatTech/ZeroBot-Plugin#173]
vps时间是正常的东八区时间，北京时间9点以后群里获取今日早报，得到的却是昨天的内容。

**Comment by fumiama** [comment]
@Jiang-Red

**Comment by Jiang-Red** [comment]
还有这种情况的嘛。。

**Comment by Jiang-Red** [comment]
手动发生"今日早报"也是这样的吗
能提供一下聊天记录的图片么
以及直接访问api看看返回的图片url日期正不正确
http://api.soyiji.com/news_jpg

**Comment by dky1996** [comment]
手动触发也不行
![image](https://user-images.githubusercontent.com/24567171/160985571-96fa42b2-fb99-4333-a316-58a1ad6e6bec.png)
![image](https://user-images.githubusercontent.com/24567171/160985664-60fe1a41-c39c-4e8b-8ce6-457b0bc174e7.png)
直接get接口日期是没问题的
![image](https://user-images.githubusercontent.com/24567171/160985843-1b277077-8e6b-4805-ab03-7e9648259e73.png)

**Comment by Jiang-Red** [comment]
是一直都晚一天，还是突然就这样了

**Comment by dky1996** [comment]
功能刚推出的时候正常的，最近更新后好像一直都是前一天了，不确定是接口变动还是什么原因

**Comment by Jiang-Red** [comment]
用job的"查看所有触发指令"

**Comment by fumiama** [comment]
> 功能刚推出的时候正常的，最近更新后好像一直都是前一天了，不确定是接口变动还是什么原因

最近更新并没有动早报

**Comment by dky1996** [comment]
什么都没动的情况下，今天的早报好了，是不是日期判断的问题？好像三月份都有延迟？

**Comment by Jiang-Red** [comment]
代码没有判断日期的地方，我自己用三月份没有一次延迟

**Comment by dky1996** [comment]
那就更诡异了，也不像是缓存了，是不是这行代码的问题
if picdata != nil && time.Since(pictime) <= time.Hour*20

**Comment by Jiang-Red** [comment]
这段是判断是否有图片数据且发送间隔是不是小于等于20小时
理应来说应该没问题

**Comment by dky1996** [comment]
也就是说如果有个群友在8点前叫了一份日报，那么从他叫日报之后的20小时内日报都不会更新？所以就造成了火星日报问题？

**Comment by Jiang-Red** [comment]
对的

**Comment by dky1996** [comment]
那这不就是逻辑问题了么。。。

**Comment by Jiang-Red** [comment]
有了定时就不会想着再去手动获取早报了，这方面确实欠考虑了

**Comment by dky1996** [comment]
大群总会有一两个性急的群友，和白天没空水群，下午或者晚上再叫一份日报的打工人

**Comment by fumiama** [comment]
可以加一个强制刷新功能

**Comment by cypress0522** [comment]
现在是api挂掉）![5b95064411826cb7.png](https://user-images.githubusercontent.com/44714368/175525413-09fc2cbe-de23-4a44-ba52-da0153e1c812.png)
