### ISSUE TITLE
wordle颜色算法bug

### ISSUE THREAD

**Issue by Miuzarte** [FloatTech/ZeroBot-Plugin#174]
此时第四行第三个“o”应是灰色
![-54746b99f17e11a6.jpg](https://user-images.githubusercontent.com/66856838/160972729-358b6077-5147-4b45-9df1-114702f70fac.jpg)

**Comment by Yiwen-Chan** [comment]
如果按照官方原版来说确实应该这样但是实际代码上实现会有些许难度

**Comment by guohuiyuan** [comment]
问题来了，官方是怎么实现的
