### ISSUE TITLE
定时触发器问题..

### ISSUE THREAD

**Issue by TomoriShino** [FloatTech/ZeroBot-Plugin#176]
![QQ图片20220402173658](https://user-images.githubusercontent.com/71255623/161377273-680e85e6-6dda-46ff-8413-081f8a974132.png)

**Comment by fumiama** [comment]
你用的是mirai吗，如果是的话，job目前不支持onebot-mirai，请尝试使用go-cqhttp。

**Comment by TomoriShino** [comment]
我用的mcl~

**Comment by cypress0522** [comment]
http也不行了![-64cf0bf6e52e61c1.png](https://user-images.githubusercontent.com/44714368/175525747-4f19fea7-f85c-4d92-864d-9f6ad8a76615.png)
