### ISSUE TITLE
wordle汉字版

### ISSUE THREAD

**Issue by zihaozhu93** [FloatTech/ZeroBot-Plugin#187]
功能名：《汉兜》（Handle），供中国的 Wordler（Wordle 玩家）游玩
功能具体：成语猜词
实现方法（可选）：项目地址，https://github.com/antfu/handle

**Comment by Yiwen-Chan** [comment]
可以参考此项目 https://github.com/MeetWq/nonebot-plugin-handle

**Comment by Yiwen-Chan** [comment]
新增至 [#2 ](https://github.com/FloatTech/ZeroBot-Plugin/issues/2#issuecomment-1094463440)
