### ISSUE TITLE
获取系统时间bug

### ISSUE THREAD

**Issue by ek1ng** [FloatTech/ZeroBot-Plugin#193]
https://github.com/FloatTech/ZeroBot-Plugin/blob/9b26eea754b76e11b03516fda5135403718042e7/plugin/score/sign_in.go#L55

go语言的time.Now()方法使用本地时间, 优先取”TZ”这个环境变量, 然后取/etc/localtime, 都取不到就用UTC兜底，我服务器上用的是UTC时间然后这里没有对获取到的时间格式做处理（默认用这个qq bot的都需要用北京时间hhh），也许可以加一个对获取到时间的校验并且封装一下，如果获取到UTC格式的时间，转换成GMT +8的格式，当然我已经修改了我服务器上的时间表示方式来解决这个问题。

**Comment by fumiama** [comment]
我们并不能假设bot一定运行在GMT +8，让用户自己更改系统时区更加灵活。因此暂不考虑增加该校验，还请谅解😂
