### ISSUE TITLE
疫情插件api的json格式似乎有变化

### ISSUE THREAD

**Issue by guohuiyuan** [FloatTech/ZeroBot-Plugin#201]
![image](https://user-images.githubusercontent.com/54976075/164201059-24c1cb20-d818-473d-b014-3d2a7bcb992a.png)

**Comment by fumiama** [comment]
谁来改一下

**Comment by Yiwen-Chan** [comment]
已修复 https://github.com/FloatTech/ZeroBot-Plugin/commit/8a0014928d9d69f19597598d57dd197811a53962
