### ISSUE TITLE
网易云点歌错误

### ISSUE THREAD

**Issue by kongbai39** [FloatTech/ZeroBot-Plugin#216]
网易点歌错误
> INFO[0371] 收到私聊消息 ‪ : 网易点歌 39
> DEBU[0371] [emojimix] msg: 网易点歌 39
> DEBU[0371] [emojimix] raw msg: 网易点歌 39
> DEBU[0371] [control] read cached moyucalendar of grp -540587985 : true
> DEBU[0374] 向服务器发送请求: {"action":"send_private_msg","params":{"message":[{"type":"music","data":{"id":"0","type":"163"}}],"user_id":540587985},"echo":14}
> DEBU[0374] 接收到API调用返回: {"data":null,"echo":14,"msg":"SEND_MSG_API_ERROR","retcode":100,"status":"failed","wording":"请参考 go-cqhttp 端输出"}
> ERRO[0374] 调用 API: send_private_msg 时出现错误, RetCode: 100, Msg: SEND_MSG_API_ERROR, Wording: 请参考 go-cqhttp 端输出

**Comment by MoYoez** [comment]
目测是API挂了.jpg

这块咱修的
