### ISSUE TITLE
塔罗牌中的皇后牌没了

### ISSUE THREAD

**Issue by guohuiyuan** [FloatTech/ZeroBot-Plugin#221]
![image](https://user-images.githubusercontent.com/54976075/167294734-6ab48658-5b8f-44e2-bc1c-27f52ff6c635.png)

**Comment by fumiama** [comment]
@shudorcl

**Comment by shudorcl** [comment]
https://gitcode.net/shudorcl/zbp-tarot/-/raw/master/MajorArcana/3.png是能够正常访问的
可能是因为之前皇后牌损坏时的cache还在
使用`run [CQ:image,file=https://gitcode.net/shudorcl/zbp-tarot/-/raw/master/MajorArcana/3.png,cache=0]` 刷新即可

**Comment by guohuiyuan** [comment]
牛的
