### ISSUE TITLE
昵称冲突

### ISSUE THREAD

**Issue by SakuraAzusa** [FloatTech/ZeroBot-Plugin#226]
今天更新1.4.0-beta7，因为有多个插件，并且使用同一昵称，在我使用别的插件功能时会提示“暂时没这功能”。
举例“XX原神签到”

还有一个问题，插件一群一天一夫一妻制群老婆，若同一个人与bot同时都在多个群里，除第一个群使用的“娶@XXX”，另外的群使用会无回应。

**Comment by SakuraAzusa** [comment]
希望可以加入一个可控的开关就行，这个提示用于提示已禁用部分zbp插件下还是不错的

**Comment by MSCxar-0293** [comment]
> 今天更新1.4.0-beta7，因为有多个插件，并且使用同一昵称，在我使用别的插件功能时会提示“暂时没这功能”。
> 举例“XX原神签到”

你的意思是「多个功能使用相似指令时会造成误触」吗？

**Comment by SakuraAzusa** [comment]
> 

是多个不同的插件导致多次的发送，例如bot的昵称为夜夜，使用命令“夜夜来张图”，插件A正常发送了，但是zbp这边也会提示“暂时没这功能”，因为上版本beta5不会提示应该是追加了什么东西

**Comment by fumiama** [comment]
zbp不可能知道其他onebot插件是否触发。另外，`暂时没这功能`实际上是触发了青云客插件。你可以通过`/禁用 aireply`关闭它。

**Comment by SakuraAzusa** [comment]
发现是停用`main.go`内插件时少停用了低优先区，已解决了感谢
