### ISSUE TITLE
签到得分版的一些问题

### ISSUE THREAD

**Issue by AinoAty** [FloatTech/ZeroBot-Plugin#235]
ERROR:Get "https://iw233.cn/api.php?sort=pc&type=json": EOF 偶尔会出现这样的报错信息

**Comment by fumiama** [comment]
@guohuiyuan 可以考虑换个API

**Comment by AinoAty** [comment]
> @guohuiyuan 可以考虑换个API

哦哦好的，请问api更改是在那个项目里的
