### ISSUE TITLE
关于塔罗牌功能的一些建议

### ISSUE THREAD

**Issue by jx9468** [FloatTech/ZeroBot-Plugin#244]
**因为发现塔罗牌的功能挺有趣味性，用的人也挺多的，但是好几个bot的塔罗牌功能都不是很完善，有点想法想说一下，希望开发者大佬有时间可以看看😆忙的话可以往后推推或者无需理会我的部分建议**

1.除了大阿卡那牌希望增加小阿卡纳牌😉

2.希望增加塔罗牌阵 常用阵以及释义可以参考[https://w.taluo.com/qz/qz.php]这里面有常用的几个牌阵，小阿卡纳牌的释义也可以参照这个网站上的。😊
   
使用方法可以参考[https://github.com/MinatoAquaCrews/nonebot_plugin_tarot]的占卜指令，

3.塔罗牌组用消息转发的方式替换原抽多张塔罗牌，例如占卜+排阵，如占卜圣三角牌阵、占卜六芒星牌阵，牌阵在上面那个塔罗牌网站里有(不要取消塔罗牌的正逆位，咱玄学也要有仪式感🤣原抽塔罗牌和解塔罗牌可以沿用。

------来自茫茫人海一个塔罗牌已弃坑路人

**Comment by jx9468** [comment]
> **因为发现塔罗牌的功能挺有趣味性，用的人也挺多的，但是好几个bot的塔罗牌功能都不是很完善，有点想法想说一下，希望开发者大佬有时间可以看看😆忙的话可以往后推推或者无需理会我的部分建议**
> 
> 1.除了大阿卡那牌希望增加小阿卡纳牌😉
> 
> 2.希望增加塔罗牌阵 常用阵以及释义可以参考[https://w.taluo.com/qz/qz.php]这里面有常用的几个牌阵，小阿卡纳牌的释义也可以参照这个网站上的。😊
> 
> 使用方法可以参考[https://github.com/MinatoAquaCrews/nonebot_plugin_tarot]的占卜指令，
> 
> 3.塔罗牌组用消息转发的方式替换原抽多张塔罗牌，例如占卜+排阵，如占卜圣三角牌阵、占卜六芒星牌阵，牌阵在上面那个塔罗牌网站里有(不要取消塔罗牌的正逆位，咱玄学也要有仪式感🤣原抽塔罗牌和解塔罗牌可以沿用。
> 
> ------来自茫茫人海一个塔罗牌已弃坑路人

**Comment by shudorcl** [comment]
#268 做了塔罗牌阵

**Comment by jx9468** [comment]
> 

现在所有塔罗牌的指令都返回的是ERROR:resp body len <= 0，是什么原因😥
[INFO] [file]已连接md5验证服务器
[INFO] [tarot]读取22张大阿尔卡纳塔罗牌
[INFO] 发送群消息(821080939): ERROR:resp body len <= 0 (id=1986687741)
[INFO] [file]关闭到md5验证服务器的连接

**Comment by shudorcl** [comment]
> > 
> 
> 现在所有塔罗牌的指令都返回的是ERROR:resp body len <= 0，是什么原因😥 [INFO] [file]已连接md5验证服务器 [INFO] [tarot]读取22张大阿尔卡纳塔罗牌 [INFO] 发送群消息(821080939): ERROR:resp body len <= 0 (id=1986687741) [INFO] [file]关闭到md5验证服务器的连接

下载[formation.json](https://github.com/FloatTech/zbpdata/blob/main/Tarot/formation.json)，然后放入`data/Tarot`文件夹中

**Comment by jx9468** [comment]
> > > 
> > 
> > 
> > 现在所有塔罗牌的指令都返回的是ERROR:resp body len <= 0，是什么原因😥 [INFO] [file]已连接md5验证服务器 [INFO] [tarot]读取22张大阿尔卡纳塔罗牌 [INFO] 发送群消息(821080939): ERROR:resp body len <= 0 (id=1986687741) [INFO] [file]关闭到md5验证服务器的连接
> 
> 下载[formation.json](https://github.com/FloatTech/zbpdata/blob/main/Tarot/formation.json)，然后放入`data/Tarot`文件夹中

可以了，大佬后面还会增加小阿卡纳牌吗😉

**Comment by shudorcl** [comment]
> > > > 
> > > 
> > > 
> > > 现在所有塔罗牌的指令都返回的是ERROR:resp body len <= 0，是什么原因😥 [INFO] [file]已连接md5验证服务器 [INFO] [tarot]读取22张大阿尔卡纳塔罗牌 [INFO] 发送群消息(821080939): ERROR:resp body len <= 0 (id=1986687741) [INFO] [file]关闭到md5验证服务器的连接
> > 
> > 
> > 下载[formation.json](https://github.com/FloatTech/zbpdata/blob/main/Tarot/formation.json)，然后放入`data/Tarot`文件夹中
> 
> 可以了，大佬后面还会增加小阿卡纳牌吗😉

老实说我没有搞懂小阿卡纳，跟大阿卡纳一样随机抽一张？还是选择一个主题抽

**Comment by jx9468** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 现在所有塔罗牌的指令都返回的是ERROR：resp body len <= 0，是什么原因😥[信息][file]已连接md5验证服务器 [INFO] [tarot]读取22张大阿尔卡纳塔罗牌 [INFO] 发送群消息（821080939）： ERROR：resp body len <= 0 （id=1986687741） [INFO] [file]关闭到md5验证服务器的连接
> > > 
> > > 
> > > 下载[formation.json](https://github.com/FloatTech/zbpdata/blob/main/Tarot/formation.json)，然后放入文件夹中`data/Tarot`
> > 
> > 
> > 可以了，大佬后面还会增加小阿卡纳牌吗😉
> 
> 老实说我没有搞懂小阿卡纳，跟大阿卡纳一样随机抽一张？还是选择一个主题抽

感觉塔罗牌细分下去就会非常复杂，正常22张大阿卡纳是可以用于平常占卜玩法，小阿卡纳是细化占卜结果的，但是小阿卡纳也可以单抽，小阿卡纳比大阿卡纳更具象，且还有专门的大阿卡纳牌阵，小阿卡纳牌阵，混合牌阵等等，太复杂了就会对使用者不太友好🤔

结论正常抽可以大小阿卡纳都抽，不用细化，太复杂了（正常一般玩的人也只看示意，不会纠结大小牌），或者抽塔罗牌默认大牌，抽小牌指定是小阿卡纳牌，牌阵也可以大小混合着来，差不多就是大小阿卡纳混一起，大小阿卡纳看解牌者自己理解。牌阵愿不愿意细化属实不强求，毕竟塔罗牌阵不少，太复杂了😂需要查的资料也不少。

**Comment by shudorcl** [comment]
https://github.com/FloatTech/ZeroBot-Plugin/pull/346 抽小阿卡纳

此外，小阿卡纳的牌阵也是随便抽一张嘛，还是说得选择指定的主体

**Comment by KafCoppelia** [comment]
@jx9468 那你帮我点个star吧哥

**Comment by jx9468** [comment]
> @jx9468 那你帮我点个star吧哥

好的大佬😉我也有用你的其他nonebot插件🥳

**Comment by jx9468** [comment]
> 
😆
嗯，随机就行了，不需要分那么细，大部分人使用也不懂那么多，其实越复杂越少人使用😂

**Comment by jx9468** [comment]
> #346 抽小阿卡纳
> 
> 此外，小阿卡纳的牌阵也是随便抽一张嘛，还是说得选择指定的主体

嗯，随机一张就行，不需要去进行详细的细分，😉大部分人使用其实不了解那么多，越复杂反而越少人使用😂

**Comment by shudorcl** [comment]
那感觉已经差不多了，可能后面调整一下看看把牌阵的牌解塞哪里比较好就行

**Comment by jx9468** [comment]
> 那感觉已经差不多了，可能后面调整一下看看把牌阵的牌解塞哪里比较好就行

感觉可以参考上面那个大佬的塔罗牌功能牌阵的的牌解，牌解和抽的塔罗牌放一起消息转发

**Comment by shudorcl** [comment]
#359 好像gocq早就修了，那就加回去吧
![image](https://user-images.githubusercontent.com/55676105/182572150-c7f7dc8a-6dd8-4289-84d1-97703c794195.png)

**Comment by shudorcl** [comment]
https://github.com/FloatTech/ZeroBot-Plugin/pull/383 大概...做完了？

**Comment by jx9468** [comment]
> [第383](https://github.com/FloatTech/ZeroBot-Plugin/pull/383)章 大概……做完了？
好的，感谢大佬😊我下班回去试一下，如无大问题就可以关闭这篇issues了，后面有bug会另开😆感谢!
