### ISSUE TITLE
nsfwauto无法禁用

### ISSUE THREAD

**Issue by TimeRainStarSky** [FloatTech/ZeroBot-Plugin#253]
只能/全局禁用nsfwauto，/禁用nsfwauto没有效果，其他服务正常，版本：v1.4.1-beta5 Windows AMD64

**Comment by fumiama** [comment]
你是不是 /全局启用 了

**Comment by TimeRainStarSky** [comment]
> 你是不是 /全局启用 了

是的，但是其他服务可以全局启用，单独禁用某个群，而这个不可以

**Comment by fumiama** [comment]
参考 #243 , 你需要
```
/改变默认启用状态 nsfwauto
```
