### ISSUE TITLE
两个机器人用@插件冲突检测出的问题

### ISSUE THREAD

**Issue by balh55y** [FloatTech/ZeroBot-Plugin#273]
机器人1开启了大部分的功能 机器人2刚部署好准备只启用几个功能
然后用@插件冲突检测时@错了,at成机器人1了
结果是1的几乎所有功能全关.
现在要开启的话只能在群内一条一条的开启吗?
有没有一键开启的功能

**Comment by fumiama** [comment]
没有，你可以删库解决问题，不过这样的话所有配置都没了。
