### ISSUE TITLE
机器人发广告是啥情况

### ISSUE THREAD

**Issue by lixd** [FloatTech/ZeroBot-Plugin#286]
help!
<img width="363" alt="D3CBCB46-E98B-4C10-A0E7-0990179644F7" src="https://user-images.githubusercontent.com/31980412/176373560-158666f4-592d-461c-9d17-a23e697072c4.png">

机器人名字是 嗷呜.
不知道是哪个插件触发的，不过应该是第三方接口返回的。

```console
$ zbp -v
* OneBot + ZeroBot + Golang
* Version 1.4.1-beta5 - 2022-06-04 17:26:44 +0800 CST
* Copyright © 2020 - 2022 FloatTech. All Rights Reserved.
* Project: https://github.com/FloatTech/ZeroBot-Plugin
```

**Comment by fumiama** [comment]
aireply
