### ISSUE TITLE
猜单词插件失效

### ISSUE THREAD

**Issue by Haorwen** [FloatTech/ZeroBot-Plugin#297]
我在前几天提交了一个pr来修复http请求的问题，但是它不起作
用![W0VTW$50 FVJ7RHJVY3TTWE](https://user-images.githubusercontent.com/62163341/177114654-43a7def1-b3fa-40e6-bf27-ed780c69a374.png)

**Comment by guohuiyuan** [comment]
这是翻译接口的问题，把翻译接口处理掉就没问题了

**Comment by Haorwen** [comment]
谢谢，已经联系接口的开发者了

**Comment by fumiama** [comment]
> 我在前几天提交了一个pr来修复http请求的问题，但是它不起作 用![W0VTW$50 FVJ7RHJVY3TTWE](https://user-images.githubusercontent.com/62163341/177114654-43a7def1-b3fa-40e6-bf27-ed780c69a374.png)

您提交前都不测试吗
