### ISSUE TITLE
部分用户数据被清了

### ISSUE THREAD

**Issue by SakuraAzusa** [FloatTech/ZeroBot-Plugin#312]
使用`score`时数据库出现了一次报错database is locked (5) (SQLITE_BUSY)，但是能正常推送消息，就是数据被清了，其他人无异常
log:
```
time="2022-07-13T00:00:42+08:00" level=info msg="收到群(*)消息 雪乃今天也要和大家一起做爱吃的布丁 : 签到"
time="2022-07-13T00:00:52+08:00" level=info msg="收到群(*)消息 草莓Ai酱 : 签到"
time="2022-07-13T00:01:00+08:00" level=info msg="[file]已连接md5验证服务器"
time="2022-07-13T00:01:04+08:00" level=info msg="[file]关闭到md5验证服务器的连接"

[35m(github.com/FloatTech/ZeroBot-Plugin/plugin/score/model.go:68)[0m 
[33m[2022-07-13 00:01:03][0m [31;1m database is locked (5) (SQLITE_BUSY) [0m
time="2022-07-13T00:01:05+08:00" level=info msg="[file]已连接md5验证服务器"
time="2022-07-13T00:01:05+08:00" level=info msg="发送群消息(*): [CQ:image,file=file:////root/zero/data/score/cache/110620061020220713signin.png] (id=-741382529)"
time="2022-07-13T00:01:08+08:00" level=info msg="[file]关闭到md5验证服务器的连接"
time="2022-07-13T00:01:09+08:00" level=info msg="发送群消息(*): [CQ:image,file=file:////root/zero/data/score/cache/220698395620220713signin.png] (id=-1530374423)"
```

**Comment by guohuiyuan** [comment]
你是不是开了两个机器人在同一个群用同一个数据库？

**Comment by SakuraAzusa** [comment]
> 你是不是开了两个机器人在同一个群用同一个数据库？

不是同一个，那台服务器上开了`gocq`,`cq-pic`,`zbp`和`ELF-RSS`,一直以来都没有冲突
同一个群确实有2个机器人，但是是在不同服务器上的

**Comment by SakuraAzusa** [comment]
问一下有指令可以把用户数据修改为之前的状态吗

**Comment by SakuraAzusa** [comment]
又有一个用户的数据被清了，发现都是凌晨零点左右使用签到时发生的问题，不知道跟环境有没有关系，环境是ubutnu20.04，有调整过系统配置，zbp是在win7上自编译的，go版本为1.18，zbp编译时版本为1.4.1（没有beta），编译时间为6月17日，发生问题时间为7月13日与16日

**Comment by guohuiyuan** [comment]
并没有，不要指望本地数据库提供数据库备份



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: 佐仓梓 ***@***.***&gt;
发送时间: 2022年7月19日 08:25
收件人: FloatTech/ZeroBot-Plugin ***@***.***&gt;
抄送: himawari ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [FloatTech/ZeroBot-Plugin] 部分用户数据被清了 (Issue #312)





 
问一下有指令可以把用户数据修改为之前的状态吗

**Comment by SakuraAzusa** [comment]
> 

我的意思是，有没有方法修改现有数据库，让丢失数据的用户分数回到之前的数值，这样就可以解决了

**Comment by guohuiyuan** [comment]
你是说签到分数，后面可以做个接口改值，也可以你自己改数据库里面的表



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: 佐仓梓 ***@***.***&gt;
发送时间: 2022年7月19日 09:54
收件人: FloatTech/ZeroBot-Plugin ***@***.***&gt;
抄送: himawari ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [FloatTech/ZeroBot-Plugin] 部分用户数据被清了 (Issue #312)





   
我的意思是，有没有方法修改现有数据库，让丢失数据的用户分数回到之前的数值，这样就可以解决了

**Comment by fumiama** [comment]
让他自己改数据库吧，编辑sql的软件一抓一大把呢

**Comment by fumiama** [comment]
@guohuiyuan 应当是因为两个人同时触发签到导致的，你可以加个反并发。
