### ISSUE TITLE
有时atri工作异常

### ISSUE THREAD

**Issue by Colorfuldiamond** [FloatTech/ZeroBot-Plugin#320]
在服务列表中看到atri已经启用，但是回复萝卜子等词汇的时候却不会回复正确信息![微信图片_20220717101736](https://user-images.githubusercontent.com/109365448/179381178-da146ebf-82d4-44b5-8cc5-721907036fbe.jpg)

**Comment by guohuiyuan** [comment]
仔细阅读readme的插件控制模块，或者去看历史问题

**Comment by Colorfuldiamond** [comment]
我已收到你的邮件这是自动回复但不代表我不会看这封邮件感谢你的耐心等待

**Comment by Colorfuldiamond** [comment]
> 仔细阅读readme的插件控制模块，或者去看历史问题
还有一个问题，在使用/改变默认启用状态将某扩展默认状态改为关闭后，再使用/改变默认启用状态却无法将其默认状态改为开启
新开一个群后其状态仍为关闭

**Comment by guohuiyuan** [comment]
搞错了，萝卜子不用@，@之后会调青云客接口

**Comment by Colorfuldiamond** [comment]
> 搞错了，萝卜子不用@，@之后会调青云客接口

是我搞错了，谢谢

**Comment by Colorfuldiamond** [comment]
发现有些时候要@才会回应，但是萝卜子@时会回复是亚托莉......萝卜子可是对机器人的蔑称，不@会发送语音



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月17日(周日) 下午5:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FloatTech/ZeroBot-Plugin] 有时atri工作异常 (Issue #320)




 
搞错了，萝卜子不用@，@之后会调青云客接口
