### ISSUE TITLE
无法改变默认启用状态

### ISSUE THREAD

**Issue by Colorfuldiamond** [FloatTech/ZeroBot-Plugin#327]
可以把默认开启的插件改为默认关闭，但是默认关闭的插件无法改为默认开启
[2022-07-18.log](https://github.com/FloatTech/ZeroBot-Plugin/files/9129294/2022-07-18.log)
三次使用/服务详情中atri均为空心圆圈
![2502c05b515037b68dcfbb149248430](https://user-images.githubusercontent.com/109365448/179441286-5a7f6673-5222-4159-9c1c-7d4d23cae84f.jpg)

**Comment by fumiama** [comment]
应当在二次反转后手动对其 /全局启用，如下图
![IMG_6817](https://user-images.githubusercontent.com/41315874/184793907-743b135c-16f5-4eac-912f-a0e57362bd05.JPEG)

**Comment by Colorfuldiamond** [comment]
我已收到你的邮件这是自动回复但不代表我不会看这封邮件感谢你的耐心等待
