### ISSUE TITLE
关于搜图与涩图功能的建议

### ISSUE THREAD

**Issue by fumiama** [FloatTech/ZeroBot-Plugin#33]
> 之前将`pic_searcher`从`setutime`分离是基于`sqlite`需要`CGO`的考量。

在x86，x86_64下`CGO`比较容易使用，但是针对`mips`、`arm`等架构进行交叉编译就相对困难，因此才将无需`sqlite`的搜图部分分离以便单独使用。
如果`sqlite`不是必须的话，建议可以将其替换为`protobuf`或`json`。

**Comment by Yiwen-Chan** [comment]
这个版本之后， `sqlite` 改用 `modernc` 写的驱动，不再需要 `CGO`
