### ISSUE TITLE
关于B站解析插件问题

### ISSUE THREAD

**Issue by HuYihe2008** [FloatTech/ZeroBot-Plugin#349]
B站解析后发出的消息中，最后的分享链接再bilibi后面会出现伪换行导致链接不完整，如下图
![IYTKO 9ECS9T`ZBS(OUF9`5](https://user-images.githubusercontent.com/76118866/182078329-fc8efb38-5930-48b3-9fa8-b972ec50893c.png)

**Comment by guohuiyuan** [comment]
没有一种可能是qq的问题

**Comment by shudorcl** [comment]
是不是协议端启用了强制消息分片，可以用手机查看bot的聊天记录，出现这种情况的话会显示为一段一段的消息。
比如这样：
![image](https://user-images.githubusercontent.com/55676105/182337830-4cd20201-95d5-4fa4-8338-386c02c6b21b.png)
![image](https://user-images.githubusercontent.com/55676105/182337877-bb33975e-cd17-4a94-8bf2-00b6c0f26895.png)

**Comment by fumiama** [comment]
强制分片现在是默认开启的，因为关闭发消息有很大概率失败。
