### ISSUE TITLE
readme中在线代码运行帮助有错误

### ISSUE THREAD

**Issue by Haorwen** [FloatTech/ZeroBot-Plugin#365]
如题，这个插件指向的网站已经403

**Comment by Jiang-Red** [comment]
![-4227c4c5f7affcfe](https://user-images.githubusercontent.com/79574799/183229084-0aa292ab-51f4-4a84-bb94-7abf6aedf633.png)
看起来我这没有问题，可能你网络问题，还是说哪个语言的用不了

**Comment by Haorwen** [comment]
嘶，我再去试试

**Comment by Haorwen** [comment]
＞和runcode之间不能有空格（（（

**Comment by Jiang-Red** [comment]
😂

**Comment by fumiama** [comment]
帮助没错吧
![help](https://user-images.githubusercontent.com/41315874/184533940-440c7a86-a809-4361-a7bd-1287d908d723.png)
