### ISSUE TITLE
linux系统下 /用法 指令无法生成图片

### ISSUE THREAD

**Issue by xry1029** [FloatTech/ZeroBot-Plugin#370]
本来应该是一个子项目的issue：
https://github.com/FloatTech/zbputils/
看到是0 open 0 closed 所以提到了这里...
涉及的文件：control/rule.go (应该)

环境信息
版本 1.5.0-beta5
运行环境 Linux(ubuntu 18.04) x86

重现步骤
在群里发送/用法 aifalse 报错无法打开data/Control/kanban.png

意见
经过测试 linux下的Zerobot无法生成指令帮助图片www
原因是linux是大小写敏感的系统而windows不是
(简单测试:将control目录链接到Control目录 问题解决了)
生成的图片存储在data/control/kanban.png 而不是 data/Control/kanban.png
把rule.go第350行的Control改成control应该能解决问题...

**Comment by fumiama** [comment]
试试最新action是否解决问题
