### ISSUE TITLE
coser插件在服务器上API接口会报错403

### ISSUE THREAD

**Issue by Loukyuu1120** [FloatTech/ZeroBot-Plugin#374]
![image](https://user-images.githubusercontent.com/29080642/184590356-68ad8c48-9d96-4b00-bb9f-9674a06dd820.png)

ERROR:status code: 403
求助有什么解决方法

**Comment by fumiama** [comment]
看看服务器能否访问这个网址，不能说明网不好，建议换个网络好的地方搭建。

**Comment by Loukyuu1120** [comment]
![image](https://user-images.githubusercontent.com/29080642/184921805-ad1ffd75-8d10-4762-ae8c-e971d998b7e4.png)
试了好几台不是国内的服务器都是403，自己的电脑能正常访问，可能是api限制国外地址访问了T T
