### ISSUE TITLE
bot祷不出来,但是能用重启大法解决

### ISSUE THREAD

**Issue by DongGua-Jun** [FloatTech/ZeroBot-Plugin#386]
![WR $32% D99_(C2E~3`A HI](https://user-images.githubusercontent.com/75875483/186374386-bf07b24d-1033-44ed-9919-0c782ade9a50.png)

如图

**Comment by MoYoez** [comment]
这应该是触发了某个功能 之前用了什么

**Comment by DongGua-Jun** [comment]
> 这应该是触发了某个功能 之前用了什么

触发原因不明捏,每天狗群员就用用早晚安,搜图,签到之类的功能
