### ISSUE TITLE
语音回复功能如何触发

### ISSUE THREAD

**Issue by Caikdd** [FloatTech/ZeroBot-Plugin#389]
RT,设置好语音模式艾特仍为文本回复,是哪里冲突了吗?
![6](https://user-images.githubusercontent.com/56495545/186823970-05b6b354-8db6-406a-8cec-ffacde9fac88.png)

**Comment by Jiang-Red** [comment]
目前release中的版本tts无法使用，请使用action编译的最新版本

**Comment by Jiang-Red** [comment]
洛阳铲，试试最新的1.5.1-beta1吧。没问题就能close了
