### ISSUE TITLE
本地setu 与 job 应该如何使用

### ISSUE THREAD

**Issue by i-ylsq** [FloatTech/ZeroBot-Plugin#390]
RT，win10 设置本地涩图一直不行
![image](https://user-images.githubusercontent.com/17917329/187149204-723207f1-64c5-4832-a1d6-eb09eed42b75.png)
以及设置本地job也不回应
![image](https://user-images.githubusercontent.com/17917329/187149645-db2a8a1d-6ddc-4edd-a620-0729a0121d46.png)
![image](https://user-images.githubusercontent.com/17917329/187150727-1ab5b00c-0a5c-4b6c-b574-75a036a8d9ca.png)

![image](https://user-images.githubusercontent.com/17917329/187150683-9458ebe0-761b-4c6f-a494-0fdce141ad18.png)

**Comment by fumiama** [comment]
在群里用
