### ISSUE TITLE
b站查成分显示ERROR:status code: 412

### ISSUE THREAD

**Issue by AFahope** [FloatTech/ZeroBot-Plugin#391]
仔细看了下 原来是拦截的意思 ...

**Comment by guohuiyuan** [comment]
设置b站cookie,把cookie设全

**Comment by guohuiyuan** [comment]
更新最新版

**Comment by Chinzicam** [comment]
> 设置b站cookie,把cookie设全
b站推送也ERROR:status code: 412，cookie重新设置了也是一样，重新设置了好几次查成分出来了一次🤔，过几分钟后又ERROR:status code: 412

**Comment by guohuiyuan** [comment]
建议开个小号，登陆非常用浏览器，拿cookie，然后关掉浏览器，这样cookie就不会更新



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: Chinzicam ***@***.***&gt;
发送时间: 2022年9月4日 23:52
收件人: FloatTech/ZeroBot-Plugin ***@***.***&gt;
抄送: himawari ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [FloatTech/ZeroBot-Plugin] b站查成分显示ERROR:status code: 412 (Issue #391)





  
设置b站cookie,把cookie设全
 b站推送也ERROR:status code: 412，cookie重新设置了也是一样，重新设置了好几次查成分出来了一次🤔，过几分钟后又ERROR:status code: 412

**Comment by AFahope** [comment]
非常感谢，成功解决
