### ISSUE TITLE
关于VITS音声请求偶现报错以及url中&符被转义的疑问

### ISSUE THREAD

**Issue by BlueCitizens** [FloatTech/ZeroBot-Plugin#394]
# 部署方式
我通过源码编译部署了plugin。

# 问题起因
首先这应当不是一个严重的问题，因为我已经着手解决了它。遗憾的是受限于我的知识，我不能完全复现它。此外，它涉及cqhttp本身的一些问题，因此它也许不在各位的工作范围内。

**总之，是否跟进这个issue完全取决于您的兴趣。**

## 后台报错
我在使用moegoe插件时，遇到了这样的错误：
```console
# 以下为cqhttp的报错
[2022-08-30 16:51:43] [WARNING]: 转换CQ码 ({"type":"record","data":{"file":"http://233366.proxy.nscc-gz.cn:8888?speaker=%E6%B4%BE%E8%92%99\u0026text=%E9%9B%AA%E8%B1%B9%E9%97%AD%E5%98%B4"}}) 到MiraiGo Element时出现错误: audio type error: text/html; charset=utf-8 将忽略本段CQ码.
[2022-08-30 16:51:43] [WARNING]: 群消息发送失败: 消息为空.

# 以下为plugin的报错
ERRO[1027] 调用 API: send_group_msg 时出现错误, RetCode: 100, Msg: SEND_MSG_API_ERROR, Wording: 请参考 go-cqhttp 端输出
```
在我第一次请求“让可莉说雪豹闭嘴”并且没有返回语音后，使用同样的请求就会持续报告该错误。它仅仅出现在我尝试请求“雪豹闭嘴”这个特定字符串时，而其他字符串都可以正常返回语音，例如“闭嘴雪豹”，“芝士雪豹”。

它也不是一个普遍的问题，因为同样的请求在其他人运行的相同bot上通常工作良好。

我使用浏览器请求了api并返回了正确的音频文件，所以我考虑CQ或运行环境本身的问题。

我注意到json字符串中url字段的&符被转义为\u0026了，但我不了解在什么情况下会转义为Unicode，这是正确的亦或是发生了某种错误？我使用打包后的cqhttp运行，且cqhttp似乎没有提供完整的log，所以我不确定是否在任何情况下都应该被转义。

我在moegoe插件的源码中插入了一行：
```go
fmt.Println(fmt.Sprintf(cnapi, url.QueryEscape(speaker), url.QueryEscape(text)))
```
以观察拼接后的url字符串。当我请求“让派蒙说雪豹闭嘴”时，控制台输出的是包含未被转义的&符：
```console
http://233366.proxy.nscc-gz.cn:8888?speaker=%E6%B4%BE%E8%92%99&text=%E9%9B%AA%E8%B1%B9%E9%97%AD%E5%98%B4
```
因为我不是go程序员，所以可能无法进一步参阅代码以解决我的问题。

## 稍后我如何解决了它
我猜测这可能是缓存问题，因为我隐约感觉到cqhttp存在某种缓存事务的手段来避免网络资源的滥用，尽管我从未实际确认过这件事情。所以我尝试移除了cqhttp/data/cache文件夹中的所有文件，这个问题如我所愿地消失了。我保留了有问题的缓存文件。

# 可能的原因
*以下只是我作为外行的猜测，我对cqhttp和Zero-Bot Plugin的架构细节都不甚了解*

我在过去几天的日志中找到了我第一次请求“雪豹闭嘴”时的行，报错和上文中的相同。在我的知识范围内，我认为是错误的url发出了错误的get请求参数，即
```
# 错误的参数
speaker: 可莉\u0026text=芝士雪豹

# 正确的参数
speaker: 可莉
text: 芝士雪豹
```
让api返回的报错信息无法被识别为audio type。并且错误的内容（返回的是错误信息文本“Missing Parameter”而不是音频文件）被缓存在了cache中，进而在后续的请求中使用了本地缓存的错误文件，导致该请求持续不可用。

此外，我还发现了许多其它相同的报错即audio type error，但当时并没有在意，所以没有跟进查错，也就无从得知当时发生什么了。

只有一点是确定的，就是缓存的确影响了我请求某一字符串的结果，它使得“让派蒙说雪豹闭嘴”这个请求至少在一定时间内（我不了解cqhttp是否有缓存过期的机制）或者在管理员着手处理前的可用性大打折扣。

**Comment by guohuiyuan** [comment]
可以在message.Image后面加一个cache=0

**Comment by fumiama** [comment]
你分析的很对，但是问题其实是请求的api自己因为请求人数过多等原因返回了不正常的结果，而gocq将该结果缓存导致后续一直使用了错误的结果，即使api本身已经恢复。所以这个问题可以通过清空缓存解决，且没有什么更好的办法，因为api本身的负载限制在那里。
