### ISSUE TITLE
管理员默认拥有权限可以开关插件

### ISSUE THREAD

**Issue by Pessqiq** [FloatTech/ZeroBot-Plugin#407]

**Comment by Pessqiq** [comment]
当群管理员没有获得机器人主人权限时可以自由启用禁用插件

**Comment by Jiang-Red** [comment]
这个一直有的啊

**Comment by Pessqiq** [comment]
这个功能可以手动关闭吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月11日(星期天) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 管理员默认拥有权限可以开关插件 (Issue #407)





 
这个一直有的啊

**Comment by Jiang-Red** [comment]
没法, 除非修改源码😂
