### ISSUE TITLE
cookie问题

### ISSUE THREAD

**Issue by Caikdd** [FloatTech/ZeroBot-Plugin#411]
RT,设置了SESSDATA仍412，我以为是账号问题换了个还是如此，所以我觉得是我cookie格式问题，所以请教一下cookie格式的问题。

**Comment by Jiang-Red** [comment]
只有sessdata不够

**Comment by Caikdd** [comment]
> 只有sessdata不够

我尝试使用SESSDATA,UserID,bili_jct设置cookie仍是412，希望可以给个提交示例，非常感激。

**Comment by Jiang-Red** [comment]
我这边是DedeUserID;DedeUserID__ckMd5;Expires;SESSDATA;bili_jct;LIVE_BUVID
手动在zbp/data/bili/config.json中的cookie位置填写试试看

**Comment by guohuiyuan** [comment]
翻了聊天记录20分钟，终于翻到了，最简单的
"cookie":"b_ut=7;buvid3=0;i-wanna-go-back=-1;innersign=0;"
