### ISSUE TITLE
Readme-插件控制下部分功能缺失介绍

### ISSUE THREAD

**Issue by SGK2401** [FloatTech/ZeroBot-Plugin#415]
这三个
- [开启 | 关闭 | 重置 | on | off | reset]看板娘
- 看板娘[@xxx]
- 看板娘图片[图片文件]

同时 '看板娘图片' 功能会在zbp重启后重置为默认的 '黑金.png'

**Comment by fumiama** [comment]
这个不太稳定，等固定下来再改 README
