### ISSUE TITLE
saucenao-关于使用以图搜图功能时出现的报错

### ISSUE THREAD

**Issue by beicuidewo** [FloatTech/ZeroBot-Plugin#418]
zbp端显示:
调用API:send_group_msg时出现错误,RetCode:100，Msg:SEND_MSG_API_ERROR,Wording:请参考go-cqhttp 端输出

cqhttp端显示:
群消息发送失败:账号可能被风控

已经排除账号问题，鉴于本人在使用中发现，除此之外，获取随机涩图时也会提示账号可能被风控，但获取随机其他类型图片时几乎没有出错，因此猜测可能是图片本身原因导致发送失败，但不知如何使机器人以聊天记录的形式来规避这种情况，故至此询问。

**Comment by Jiang-Red** [comment]
随机涩图是setutime这个插件, setutime是用的数据库存储pid的方式, 其中可能有些失效了
以图搜图的报错可以在zbp启动命令行参数中添加-d来打开debug模式以获得更多日志
改成合并转发聊天记录形式并不能解决真的被风控的问题

**Comment by beicuidewo** [comment]
好的，谢谢解答!
顺带一提还真是我账号的问题，今早起床发现账号被冻结了一天，但是此前在安全中心却显示一切正常，我换了另一个小号再去启动这个服务，就一切正常了，不过不管怎么说，谢谢dalao回答我的问题!
