### ISSUE TITLE
团队七阶猜单词无响应

### ISSUE THREAD

**Issue by Haorwen** [FloatTech/ZeroBot-Plugin#424]
如题，五级、六级都可以使用，七阶的话发单词没有回应

**Comment by Jiang-Red** [comment]
![image](https://user-images.githubusercontent.com/79574799/192011586-4e4c98f6-0e92-407b-9d1f-4bdac8c0a5c4.png)
实测没问题，版本v1.5.1-beta4，并且最近应该没动过这个插件才对

**Comment by guohuiyuan** [comment]
> 如题，五级、六级都可以使用，七阶的话发单词没有回应

提issue最好附个图

**Comment by Haorwen** [comment]
也许是我网络环境的问题（）
