### ISSUE TITLE
v1.5.1 beta4 md5不匹配

### ISSUE THREAD

**Issue by Moswde** [FloatTech/ZeroBot-Plugin#427]
INFO[0000] [file]已连接md5验证服务器                            
INFO[0000] [file]从镜像下载数据2字节...                          
ERRO[0000] [file]文件 data/Control/kanban.png md5不匹配, 下载失败 
panic: file md5 mismatch

goroutine 1 [running]:
github.com/FloatTech/zbputils/control.init.2()
        github.com/FloatTech/zbputils@v1.5.1-0.20220922024334-73bc7af39d08/control/servicepic.go:77 +0x85

**Comment by kikasyou** [comment]
我也是这个问题！+1，删了control/kanban.png也不行

**Comment by Moswde** [comment]
问下注释百人一首插件的具体操作

**Comment by kikasyou** [comment]
> 问下注释百人一首插件的具体操作

你用的是发行版，没法禁用的。如果是本地编译，在main.go里注释上面那一行即可。

> 本地直接运行：
> 下载安装最新 [Go](https://studygolang.com/dl) 环境
> 下载本项目[压缩包](https://github.com/FloatTech/ZeroBot-Plugin/archive/master.zip)，本地解压
> 编辑 main.go 文件，内容按需修改
> 运行 OneBot 框架
> Windows下双击 run.bat 文件，Linux下使用 run.sh 运行本插件

**Comment by Moswde** [comment]
我加入注释后仍报错panic: invalid csvfile，查询是百人一首这个插件的文件，goroutine 由50变为40

**Comment by Moswde** [comment]
求个注释的具体操作

**Comment by 1062367287** [comment]
我也是这个错误，总之就是把https://github.com/FloatTech/zbpdata的文件全部下载到data里面然后把那个百人一首注释掉，我这边已经好了

**Comment by 1062367287** [comment]
我也是这个问题，总之就是把[https://github.com/FloatTech/zbpdata](url)下的文件下载到data里面去，然后再注释掉hyaku插件

**Comment by Moswde** [comment]
怎么注释呢，把"github.com/FloatTech/ZeroBot-Plugin/plugin/hyaku"加到import里吗？
&nbsp;


233
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月2日(星期天) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] v1.5.1 beta4 md5不匹配 (Issue #427)





 
我也是这个问题，总之就是把https://github.com/FloatTech/zbpdata下的文件下载到data里面去，然后再注释掉hyaku插件

**Comment by Moswde** [comment]
怎么注释呢，把"github.com/FloatTech/ZeroBot-Plugin/plugin/hyaku"加到import里吗？

**Comment by Moswde** [comment]
帮我指出一下，废物不会弄

//go:build ignore
// +build ignore
// _ "github.com/FloatTech/ZeroBot-Plugin/plugin/hyaku" // 百人一首
package main

import (
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"strings"
	"unicode"
	"unsafe"
	"github.com/FloatTech/ZeroBot-Plugin/plugin/hyaku"
	"github.com/wdvxdr1123/ZeroBot/utils/helper"
)

func main() {
	var files []string
	fs.WalkDir(os.DirFS("./"), ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.Contains(path, "/") && unicode.IsUpper([]rune(path)[0]) {
			files = append(files, path)
		}
		return nil
	})
	fmt.Println(files)
	md5s := make([]string, len(files))
	for i, fn := range files {
		data, err := os.ReadFile(fn)
		if err != nil {
			panic(err)
		}
		buf := md5.Sum(data)
		*(*unsafe.Pointer)(unsafe.Pointer(&md5s[i])) = unsafe.Pointer(&buf)
		*(*uintptr)(unsafe.Add(unsafe.Pointer(&md5s[i]), unsafe.Sizeof(uintptr(0)))) = uintptr(16)
	}
	r := registry.NewRegedit("reilia.fumiama.top:32664", "fumiama", os.Getenv("REILIA_SPS"))
	err := r.Connect()
	if err != nil {
		panic(err)
	}
	for i, fn := range files {
		for c := 0; c < 5; c++ {
			err = r.Set("data/"+fn, md5s[i])
			fmt.Println("set", "data/"+fn, "=", hex.EncodeToString(helper.StringToBytes(md5s[i])))
			if err == nil {
				break
			}
			if c >= 4 {
				panic("ERROR:" + err.Error() + "max retry times exceeded")
			} else {
				fmt.Println("ERROR:", err, ", retry times:", c)
			}
			_ = r.Close()
			err = r.Connect()
			if err != nil {
				panic(err)
			}
		}
	}
	_ = r.Close()
}

**Comment by 1062367287** [comment]
main.go里面第89行（我是89行）的	
_ "github.com/FloatTech/ZeroBot-Plugin/plugin/hyaku"         // 百人一首 
加个//

**Comment by Moswde** [comment]
我的main.go里找不到是我下错了吗？

**Comment by 1062367287** [comment]
&nbsp;那你是用什么启动的？


&nbsp;


丁宇梁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月2日(星期天) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] v1.5.1 beta4 md5不匹配 (Issue #427)





 
我的main.go里找不到是我下错了吗？

**Comment by Moswde** [comment]
要不把改好的发给我一下？

**Comment by 1062367287** [comment]
qq：1062367287


&nbsp;


丁宇梁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月2日(星期天) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] v1.5.1 beta4 md5不匹配 (Issue #427)





 
要不把改好的发给我一下？

**Comment by fanjinchi** [comment]
发行版的不在main.go而是bot.go里了老哥

**Comment by ktur6443** [comment]
大佬能讲一下怎么手动获取数据库吗

**Comment by Jiang-Red** [comment]
鉴于 hyaku 插件的 hyaku.csv 下载依旧无法成功, 这里也可以手动进行下载并放置到 zbp/data/hyaku 下

**Comment by ktur6443** [comment]
time="2022-10-03T23:43:34+08:00" level=info msg="[file]已连接md5验证服务器"
time="2022-10-03T23:43:35+08:00" level=info msg="[file]从镜像下载数据2字节..."
time="2022-10-03T23:43:35+08:00" level=error msg="[file]文件 data/Control/kanban.png md5不匹配, 下载失败"
panic: file md5 mismatch

goroutine 1 [running]:
github.com/FloatTech/zbputils/control.init.2()
        github.com/FloatTech/zbputils@v1.5.1-0.20220922024334-73bc7af39d08/control/servicepic.go:77 +0x85

**Comment by Jiang-Red** [comment]
> time="2022-10-03T23:43:34+08:00" level=info msg="[file]已连接md5验证服务器" time="2022-10-03T23:43:35+08:00" level=info msg="[file]从镜像下载数据2字节..." time="2022-10-03T23:43:35+08:00" level=error msg="[file]文件 data/Control/kanban.png md5不匹配, 下载失败" panic: file md5 mismatch
> 
> goroutine 1 [running]: github.com/FloatTech/zbputils/control.init.2() github.com/FloatTech/zbputils@v1.5.1-0.20220922024334-73bc7af39d08/control/servicepic.go:77 +0x85

你可以手动在zbp目录下git clone [zbpdata](https://github.com/FloatTech/zbpdata)
或者使用[action编译](https://github.com/FloatTech/ZeroBot-Plugin/actions/runs/3175360053)版本
