### ISSUE TITLE
原神VITS API离线

### ISSUE THREAD

**Issue by Stardust-minus** [FloatTech/ZeroBot-Plugin#428]
如题。
API目前已不再运行。
这里放出模型，可供部署到云函数
http://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth
Cleaner见https://github.com/Stardust-minus/vits/tree/main/text

**Comment by fumiama** [comment]
好，我试试

**Comment by baiqilingnai** [comment]
这个整了是不是只能自己一个人用

**Comment by kikasyou** [comment]
原来如此，感谢分享，V.

**Comment by fumiama** [comment]
已部署。

**Comment by zmndan3** [comment]
http://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth 已无法访问
有大佬有存档吗

**Comment by lrioxh** [comment]
> 

https://huggingface.co/lrioxh/vits/tree/main
