### ISSUE TITLE
qqwife插件, 超级用户娶指定群友, 未能登记到数据库

### ISSUE THREAD

**Issue by tkgs0** [FloatTech/ZeroBot-Plugin#433]
以下是我的操作步骤:
- 将Oct 5, 2022更新的代码pull到本地, 
- 按照README.md给出的步骤编译成二进制文件zbp, 
- 删除了已有的db文件并运行zbp, 
- 超级用户发送 `重置所有花名册` ,
- 超级用户发送 `娶@xxxxx` ,
- 普通用户发送 `娶@xxxxx` ,

问题依然存在.
控制台未报错, 以下为发生问题的聊天截图
![Screenshot_20221006_122317_com tencent mobileqq](https://user-images.githubusercontent.com/107618388/194215644-5565714e-6104-4dc7-acaa-9a50f15a4140.jpg)

**Comment by fumiama** [comment]
@fangliuyu

**Comment by fangliuyu** [comment]
@tkgs0 2天前刚提交了新的代码，请问是否更新了？

**Comment by tkgs0** [comment]
> @tkgs0 2天前刚提交了新的代码，请问是否更新了？

更新了, 我昨天pull的
