### ISSUE TITLE
midi简易制作有没有办法转成音频发送

### ISSUE THREAD

**Issue by CCYellowStar** [FloatTech/ZeroBot-Plugin#434]
如题

**Comment by weigui404** [comment]
装ffmpeg

**Comment by CCYellowStar** [comment]
已经装了，好像默认发的文件

**Comment by MoYoez** [comment]
系统变量可配置了（

**Comment by guohuiyuan** [comment]
那是因为timidity转换失败才发的midi文件，看看timidity是否正常安装，并配置环境变量

**Comment by ShiinaMono** [comment]
[CQ:record,file=file:////home/ubuntu/zero/data/midicreate/cache/229748829220230415102142_midicreate.wav]
请问这是为啥，record限制了？😭
