### ISSUE TITLE
权限建议

### ISSUE THREAD

**Issue by DDGG123** [FloatTech/ZeroBot-Plugin#441]
玩更新后的qqwife的时候，两个群管理互相打闹，疯狂改cd，结果变成了比手速＋刷屏，bot主人使用 /禁止 service qq1 qq2... (禁止 qqs 使用服务 service)命令试图终结这场骚乱时，反而被偷学了命令，并且该命令对bot主人也生效，最后使用 /封禁 qq1 qq2... (禁止 qqs 使用全部服务)后才终止了这场骚乱。不过即使被封禁后，他们依然可以使用 /禁止 service qq1 qq2... (禁止 qqs 使用服务 service)命令来阻止bot主人来使用qqwife插件，虽然是一场无关紧要的闹剧，不过能优化一下是再好不过了！

**Comment by fumiama** [comment]
因为管理员本身就可以使用禁言功能，因此为管理赋予了禁用启用的权限，更改这个权限会改变当前的行为模式，因此暂不考虑更改。这种情况建议不要将bot放在自己无法控制的群里，封号风险很大。
**p.s. 若果有相同需求，请跟此贴，如果人数较多，将考虑其它解决方案。**

**Comment by liuth212** [comment]
跟，能不能出一个可调的，让某些功能只能主人使用

**Comment by Mubanjun** [comment]
跟帖，需要，**非常需要！**
