### ISSUE TITLE
设置看板娘图片，无反应

### ISSUE THREAD

**Issue by guyingd** [FloatTech/ZeroBot-Plugin#443]
之前可以设置看板娘图片，但今天我重新拉取代码运行后，发出的设置指看板娘图片只反馈了一条"请发生一张图片"后无反应
![Screenshot_2022-10-11-00-26-40-868_com tencent mobileqq](https://user-images.githubusercontent.com/79262296/194914623-60e38257-66b4-4849-92ba-bff68826fd9b.jpg)
![IMG20221011002728](https://user-images.githubusercontent.com/79262296/194914658-7da5aefc-cef4-4d5f-ab35-8dbe42cb7c12.jpg)

**Comment by kikasyou** [comment]
私聊可以，自己要得是主人。
