### ISSUE TITLE
无法在线运行代码

### ISSUE THREAD

**Issue by 315923876** [FloatTech/ZeroBot-Plugin#446]
![4D0ABF5A-9BE5-433A-A178-755D84EA4D51](https://user-images.githubusercontent.com/115673942/195472886-39918cb1-350b-4f93-9832-e854595eb8c5.png)
跑在Windowsserver2019上，安装了py，其他功能运行正常，请问这个是什么原因啊

**Comment by 315923876** [comment]
![Uploading E1D27562-5325-43B4-BB4E-601AFCBD2F91.png…]()

**Comment by fumiama** [comment]
建议学习python语法
[Python 基础教程](https://m.runoob.com/python/python-tutorial.html)

**Comment by 315923876** [comment]
> 建议学习python语法
> [Python 基础教程](https://m.runoob.com/python/python-tutorial.html)

对不起，也许我截的图不对，我是把示例命令拷贝进去运行的，输出结果仍然是报错
>runcode python
print("Hello, World!")

**Comment by 315923876** [comment]
![714B4924-A8B0-4AB2-9036-FC1AE0760FDB](https://user-images.githubusercontent.com/115673942/195500847-d4d33f11-5500-4be0-808e-d494ec14495c.png)

**Comment by fumiama** [comment]
有人有相同问题吗

**Comment by guohuiyuan** [comment]
好像是寄了，以前有效的，现在无效了

**Comment by Haorwen** [comment]
我也无法使用

**Comment by fumiama** [comment]
fix runcode at 3339b6a16fb5ae02529f8f74d9b5ba161816ea4f
