### ISSUE TITLE
建议给ai绘图加个自动撤回的配置项

### ISSUE THREAD

**Issue by Haorwen** [FloatTech/ZeroBot-Plugin#460]
或者屏蔽词也可以，nsfw词条有的时候害人（

**Comment by fumiama** [comment]
屏蔽词请看插件`antiabuse`，自动撤回请问 @guohuiyuan

**Comment by Haorwen** [comment]
好

**Comment by Haorwen** [comment]
![image](https://user-images.githubusercontent.com/62163341/196092207-b19f689e-255b-4b21-980d-1b0c09431486.png)
违禁词插件有问题啊（
