### ISSUE TITLE
关于日语相关功能

### ISSUE THREAD

**Issue by jx9468** [FloatTech/ZeroBot-Plugin#469]
1.日语语法功能，语法功能标签范围太广了，如查询语法'な'会从n1到n5的语法里随机一个，指定N几也是随机语法😂，而ない，～から～まで，～ですから等之类的则完全无法查询🤦‍♂️现在个人感觉处于一种鸡肋不太好用的感觉，请问是否可以支持多标签或者模糊匹配语法这里解决？

2.日语听力功能，目前只有“随机日语听力”“随机日语歌曲”有用，但是指定查询几乎完全没用🤣比如“日语听力 新标准日本语”这种指令可以使用，但是完全无法指定标准课文内容或者单词，而像指定jptingroom官网标题如“日语听力 新版标准日本语初级(上册课文) 02”这种名字则无响应后台也无报错。
而且还有问题就是自己查询的“日语听力 新标准日本语”这种，出来的也只有图没有音频，歌曲也是一样。只有随机听力歌曲会有音频。

**Comment by fumiama** [comment]
@guohuiyuan

**Comment by guohuiyuan** [comment]
第一个可以加查询，初衷是随手记，第二个没有可能真没有，或者没爬完整
