### ISSUE TITLE
关于zerobot的bililibilipush插件：412问题

### ISSUE THREAD

**Issue by beicuidewo** [FloatTech/ZeroBot-Plugin#498]
查成分查弹幕正常，添加订阅也正常
但是每当拉取b站推送有东西可以发送的时候，bot并不会正常发到群里，而是疯狂私聊我：Error: bilibilipush,status code: 412
完整的b站cookie也已经设置好，使用了login_bili_go获取。
这并非新问题，在几个版本之前的zerobot也曾发生过。
想知道这种方法我该如何处理~

另：music插件的qq点歌经常性的寄，但是网易云点歌几乎没有失败过，有没有什么办法可以手动设置默认点歌途径？
感谢dalao！
![image](https://user-images.githubusercontent.com/112927917/201475121-617108ce-9bb5-45c4-bcb4-c0d0cfb1177d.png)

**Comment by Jiang-Red** [comment]
如图, 推荐拉取间隔不要过快
![image](https://user-images.githubusercontent.com/79574799/201482520-4f720e80-e043-4948-a105-8314c8da2ef3.png)

**Comment by beicuidewo** [comment]
> 如图, 推荐拉取间隔不要过快 ![image](https://user-images.githubusercontent.com/79574799/201482520-4f720e80-e043-4948-a105-8314c8da2ef3.png)

我想我知道为什么会弹出412了：我同时在三个群调用@every 10m触发的“拉取b站推送”，它们一起请求导致请求频率太高所以一起蹦412了。我给不同的群设置不同时间的触发就好了，现在问题已经解决了！感谢dalao

**Comment by Jiang-Red** [comment]
~~但是。全局只需要设置一个就好了~~
