### ISSUE TITLE
关于VITS音声请求&字符被转换成\u0026的问题

### ISSUE THREAD

**Issue by EverDarling** [FloatTech/ZeroBot-Plugin#502]
1. ### 部署方式
    直接使用了gocqzbp，环境是Windows
2. ### gocqhttp端输出
   

> [2022-11-20 15:39:23] [WARNING]: 转换CQ码 ({"type":"record","data":{"file":"https://genshin.azurewebsites.net/api/speak?format=mp3\u0026text=%E4%B8%8D%E5%8E%BB\u0026id=0"}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exit status 1 将忽略本段CQ码.

实际上上面的音频文件地址在浏览器中输入会得到”https://genshin.azurewebsites.net/api/speak?format=mp3\u0026text=不去\u0026id=0“，也就是说原本的"&"被转成了Unicode字符编码"\u0026"，导致网址不能被解析，最后无法输出相应的CQ码

因为我是拿现成的版本来使用，并没有对代码作出任何修改，也不清楚这种现象产生的原因，希望能得到帮助

**Comment by Yiwen-Chan** [comment]
实际 `CQ码` 中的"&"字符并没有被转义为"\u0026"，仅仅是日志显示问题，而无法访问可能是云函数访问的问题，可以试试和姬气人说 `run[CQ:record,file=https://genshin.azurewebsites.net/api/speak?format=mp3&text=%E4%B8%8D%E5%8E%BB&id=0,cache=0]` 刷新缓存

**Comment by EverDarling** [comment]
> 实际 `CQ码` 中的"&"字符并没有被转义为"\u0026"，仅仅是日志显示问题，而无法访问可能是云函数访问的问题，可以试试和姬气人说 `run[CQ:record,file=https://genshin.azurewebsites.net/api/speak?format=mp3&text=%E4%B8%8D%E5%8E%BB&id=0,cache=0]` 刷新缓存

测试结果如图：
![image](https://user-images.githubusercontent.com/53330091/202894773-fbcf29f3-048d-4c65-9fa1-fdcb9e5e7e13.png)
没加cache=0可以正常发出，加了则不能正常转换
而让XX说XX指令本身仍然没有反应

**Comment by Yiwen-Chan** [comment]
云函数本身问题，将就着用吧

**Comment by EverDarling** [comment]
原来如此，谢谢解答，期待之后版本能修复这个问题
