### ISSUE TITLE
我是用方法二的部署失败

### ISSUE THREAD

**Issue by hushilibg** [FloatTech/ZeroBot-Plugin#506]
#10 0.998 /nix/store/zzpcf8ysd51a82rfhbs1wpygi1hqi6wp-dotnet-sdk-6.0.400/sdk/6.0.400/NuGet.targets(369,5)：错误 MSB3202：项目文件“/app/找不到 src/PluginCore/src/PluginCore/PluginCore.csproj”。[/app/QQBotHub.sln]
#10 0.998 /nix/store/zzpcf8ysd51a82rfhbs1wpygi1hqi6wp-dotnet-sdk-6.0.400/sdk/6.0.400/NuGet.targets(369,5)：错误 MSB3202：项目文件“/app/ src/PluginCore/src/PluginCore.IPlugins/PluginCore.IPlugins.csproj”找不到。[/app/QQBotHub.sln]
#10 0.998 /nix/store/zzpcf8ysd51a82rfhbs1wpygi1hqi6wp-dotnet-sdk-6.0.400/sdk/6.0.400/NuGet.targets(369,5)：错误 MSB3202：项目文件“/app/ src/PluginCore/src/PluginCore.AspNetCore/PluginCore.AspNetCore.csproj”找不到。[/app/QQBotHub.sln]
#10 0.998 /nix/store/zzpcf8ysd51a82rfhbs1wpygi1hqi6wp-dotnet-sdk-6.0.400/sdk/6.0.400/NuGet.targets(369,5)：错误 MSB3202：项目文件“/app/ src/PluginCore/src/PluginCore.IPlugins.AspNetCore/PluginCore.IPlugins.AspNetCore.csproj”找不到。[/app/QQBotHub.sln]
#10 0.998 /nix/store/zzpcf8ysd51a82rfhbs1wpygi1hqi6wp-dotnet-sdk-6.0.400/sdk/6.0.400/NuGet.targets(369,5)：错误 MSB3202：项目文件“/app/ docker-compose.dcproj”没有找到。[/app/QQBotHub.sln]
 
#10 错误：执行程序运行失败 [/bin/bash -ol pipefail -c dotnet restore]：退出代码：1
-----
> [6/9] 运行 dotnet 恢复：
-----
执行程序运行失败 [/bin/bash -ol pipefail -c dotnet restore]：退出代码：1
 
错误：Docker 构建失败

**Comment by Yiwen-Chan** [comment]
你走错地方了
