### ISSUE TITLE
Question:是否可以替换tts的api？

### ISSUE THREAD

**Issue by Stardust-minus** [FloatTech/ZeroBot-Plugin#542]
如题。
这里有一个新炼的139人模型（原神+崩坏3），是否可以替换之前的api？
（因为我你们那看已经部署到云函数了）
![image](https://user-images.githubusercontent.com/52093397/209466887-ba81bb23-5eec-4823-9bc3-d250af8418f2.png)

**Comment by fumiama** [comment]
可以，需要你提供模型和config.json。另外，你也可以自己部署，使用azure云函数即可。 https://github.com/fumiama/MoeGoe/tree/genshin 这里将模型放在根目录，然后修改genshin.json。

**Comment by Stardust-minus** [comment]
已提交PR
