### ISSUE TITLE
bug 猜歌功能反复使用后无响应

### ISSUE THREAD

**Issue by 502milk** [FloatTech/ZeroBot-Plugin#545]
![DRU(%XCAZC2S@AL`)`PDRY4](https://user-images.githubusercontent.com/49502047/209529019-1a46ee94-bebe-4ee7-a17f-37ef55458cc7.png)
![QQ截图20221226165905](https://user-images.githubusercontent.com/49502047/209529033-d99f42fb-7840-4088-99ce-033c788d1fd0.png)
![QQ截图20221226165921](https://user-images.githubusercontent.com/49502047/209529034-f7aa3784-c0b1-4626-bff8-59b0269409db.png)
其他功能正常·-·
系统Win11
zbp版本1.6.0

**Comment by fumiama** [comment]
@fangliuyu

**Comment by jun8848** [comment]
快救救群友 群友没有猜歌不能活了

**Comment by fangliuyu** [comment]
谢邀，当前插件与config的latency参数有所冲突。临时对策是将latency参数调小。等待问题修复后再调回来即可

**Comment by fangliuyu** [comment]
@502milk @jun8848 十分抱歉，我无法复现该issue。下列链接为我目前的解决方案，请你们帮忙试试是否可以解决当前issue.

[https://github.com/fangliuyu/ZeroBot-Plugin/blob/master/plugin/guessmusic/guessmusic.go](https://github.com/fangliuyu/ZeroBot-Plugin/blob/master/plugin/guessmusic/guessmusic.go)
