### ISSUE TITLE
bug 签到无法使用

### ISSUE THREAD

**Issue by 2055135** [FloatTech/ZeroBot-Plugin#548]
![image](https://user-images.githubusercontent.com/119772101/209773382-4bcb095d-0cd2-4241-98d5-e504153b9d62.png)
![image](https://user-images.githubusercontent.com/119772101/209773543-9fd18f37-c96a-48cb-9e02-6a6dbc559ceb.png)
群友经常经常使用该功能，希望能尽快修好，谢谢
zerobot版本1.6.1-beta3
Windows版本
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎11/‎12
操作系统版本	22621.963
体验	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by fumiama** [comment]
试试最新action版
