### ISSUE TITLE
关于图片上传失败: image type error: application/octet-stream报错

### ISSUE THREAD

**Issue by YouYouLip** [FloatTech/ZeroBot-Plugin#551]
这个报错我查了一个 一开始是？报错，查了一下发现是plugin/atri文件报错
![image](https://user-images.githubusercontent.com/119958263/210150021-9395645a-34bd-4e25-aa8f-5ff148d6dde4.png)
![image](https://user-images.githubusercontent.com/119958263/210150051-c110c989-ab48-48c5-8960-9f82eb5f397c.png)
![image](https://user-images.githubusercontent.com/119958263/210150066-618da26d-1024-4954-be16-1770519b6e52.png)
是jpg文件我没有下载还是什么原因么？

**Comment by YouYouLip** [comment]
还是说atri插件的图像api寄了（惊！？）

**Comment by fumiama** [comment]
是的，ATRI所用图床gitcode增加了反扒，目前发图是失效状态。考虑之后修复。

**Comment by YouYouLip** [comment]
> 是的，ATRI所用图床gitcode增加了反扒，目前发图是失效状态。考虑之后修复。

这样啊 了解了（悲）
