### ISSUE TITLE
更新后 功能 [浅草寺求签/女装] 异常，无法正常输出图像

### ISSUE THREAD

**Issue by ultragalaxy2018** [FloatTech/ZeroBot-Plugin#561]
如题，更新后出现黑图现象
![image](https://user-images.githubusercontent.com/41445799/212520009-6611ebed-050a-44ab-8b11-bf34b204265a.png)
![image](https://user-images.githubusercontent.com/41445799/212520016-634b85b3-b0f3-4fe0-a1fe-e021de4b8400.png)
![image](https://user-images.githubusercontent.com/41445799/212520029-33ca025b-d117-43a1-bad5-afc37e2893cd.png)

**Comment by Jiang-Red** [comment]
相关问题已修复，等待下个版本升级依赖
