### ISSUE TITLE
更新至最新版本以后ai绘图出错

### ISSUE THREAD

**Issue by TheShy-Dream** [FloatTech/ZeroBot-Plugin#564]
![image](https://user-images.githubusercontent.com/58178926/214592935-0f85384b-b6b1-420b-a798-fea49ebdb81e.png)
不仅无法设置配置 而且在调用的时候报了错
![image](https://user-images.githubusercontent.com/58178926/214593064-cac1a472-078f-47bc-ad63-eba193875c7a.png)
使用的是最新版本，不知道这个功能是否存在，我使用的是release本仓库的方式部署，求大佬指点

**Comment by Jiang-Red** [comment]
1. 请检查是否成功配置主人qq号
2. 请检查token是否被api方记录
