### ISSUE TITLE
搜图功能下载图片失败

### ISSUE THREAD

**Issue by ultragalaxy2018** [FloatTech/ZeroBot-Plugin#567]
![image](https://user-images.githubusercontent.com/41445799/215407101-58a98125-269b-41ad-945f-8263fe472951.png)
如图，一直提示invalid image size，然后就什么都发不出，如果再发送一次搜图指令，会直接发送图片路径，但是在图片路径下什么文件也没有

**Comment by ultragalaxy2018** [comment]
是否可以通过修改./plugin/saucenao/下的searcher.go中如图的链接以更换图片代理？
![image](https://user-images.githubusercontent.com/41445799/215408053-7acdc9bc-e422-4ae1-9adb-5d6f89e69887.png)

**Comment by Yiwen-Chan** [comment]
看报错结果像是在拼接CQ码的时候没把文件名拼接上导致出错，请提供更详细的zbp的日志

**Comment by ultragalaxy2018** [comment]
> 看报错结果像是在拼接CQ码的时候没把文件名拼接上导致出错，请提供更详细的zbp的日志

详细日志具体在哪儿提取呢？我是使用的第二类配置方案本地直接运行，没看到类似log的输出文件，只能找到go-cqhttp的log

**Comment by Yiwen-Chan** [comment]
该图片被P站标记为R-18内容，因此无法显示
