### ISSUE TITLE
好多涉及到生成文字图的图片里大部分文字是乱码

### ISSUE THREAD

**Issue by rednoon** [FloatTech/ZeroBot-Plugin#583]
是我没装什么东西吗？需要进行什么设置吗？
比如b站推送列表
![QSL57$CGZU}1`EJ(9 20VRK](https://user-images.githubusercontent.com/38847486/218276612-9ea67644-f4aa-4e16-9f1b-1725e1a57e5a.PNG)
比如用xxx渲染文字
![2($7E){O2$S2_{%2XPKLIW3](https://user-images.githubusercontent.com/38847486/218276625-e9fdf686-ebb7-4ab1-a6fe-92933d593cbe.PNG)
比如日语语法
![N889 3H7N1HMH1O6}EJE99T](https://user-images.githubusercontent.com/38847486/218276600-868dbb7f-9ef6-4f01-95c7-1954606f80ae.PNG)

**Comment by Jiang-Red** [comment]
下个版本修复

**Comment by fumiama** [comment]
fixed
