### ISSUE TITLE
[BUG] 无限娶群友

### ISSUE THREAD

**Issue by Miuzarte** [FloatTech/ZeroBot-Plugin#585]
# 版本：v1.6.2-beta3
![) AHIIX51W4233Q5 A9E$HD](https://user-images.githubusercontent.com/66856838/218419773-851848d9-2a40-4bf0-b289-d21420150153.png)

**Comment by Jiang-Red** [comment]
删除data/qqwife底下的db文件

**Comment by fumiama** [comment]
@guohuiyuan

**Comment by fangliuyu** [comment]
@Miuzarte 
你好，请使用“重置所有花名册”指令后反馈一下信息

**Comment by Miuzarte** [comment]
> @Miuzarte 你好，请使用“重置所有花名册”指令后反馈一下信息

重启删了db之后没问题了
