### ISSUE TITLE
以图搜图分开发会报错，自测百分百复现，并且一起发 ascii2d搜图没法出结果

### ISSUE THREAD

**Issue by chenyue314** [FloatTech/ZeroBot-Plugin#586]
![image](https://user-images.githubusercontent.com/21164819/218805572-aeb996da-15b5-48ee-84f2-9f1c97fa08ed.png)

[ERROR] [bot] execute handler err: interface conversion: interface {} is nil, not []string
goroutine 2754 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/wdvxdr1123/ZeroBot.match.func2.1.1()
        github.com/wdvxdr1123/ZeroBot@v1.6.8/bot.go:250 +0x45
panic({0x11ecae0, 0xc0002adf20})
        runtime/panic.go:884 +0x212
github.com/FloatTech/ZeroBot-Plugin/plugin/saucenao.init.0.func2(0xc00008a820)
        github.com/FloatTech/ZeroBot-Plugin/plugin/saucenao/searcher.go:113 +0x15de
github.com/wdvxdr1123/ZeroBot.match.func2.1()
        github.com/wdvxdr1123/ZeroBot@v1.6.8/bot.go:253 +0x68
created by github.com/wdvxdr1123/ZeroBot.match.func2
        github.com/wdvxdr1123/ZeroBot@v1.6.8/bot.go:246 +0xaa

合并图片发，没有ascii2d搜图的结果

![image](https://user-images.githubusercontent.com/21164819/218805989-cb09f00d-664a-402a-b291-01459ad1fb6b.png)

**Comment by MoYoez** [comment]
搜图saucenao是第一优先的，这个结果了就不会触发ascii2d
没有才会向下查找

**Comment by fumiama** [comment]
fixed.

**Comment by 555tr** [comment]
现在分开发还是查不了
![image](https://user-images.githubusercontent.com/110760205/224655469-5e0d6365-7f4e-4617-9a21-4c64958de8b7.png)
![image](https://user-images.githubusercontent.com/110760205/224655693-3cb8c5ab-a3e3-4599-9915-cd31c01784cd.png)
![image](https://user-images.githubusercontent.com/110760205/224655795-715038fa-b808-40b5-bc36-40fb32753ac0.png)
![image](https://user-images.githubusercontent.com/110760205/224656046-415572a5-62fb-4360-9329-cc5abf9f724e.png)

**Comment by 555tr** [comment]
> fixed.

分开发还是查不到，提示未获取图片链接

**Comment by 315923876** [comment]
@fumiama

**Comment by fumiama** [comment]
试试最新

**Comment by 555tr** [comment]
> 试试最新

可以了，谢谢你
