### ISSUE TITLE
添加b站订阅功能，EOE团队的成员都无法成功订阅（包括官号）

### ISSUE THREAD

**Issue by rednoon** [FloatTech/ZeroBot-Plugin#589]
![image](https://user-images.githubusercontent.com/38847486/219843177-cff880cc-6f94-45a9-beda-ebf47e47ab99.png)
![image](https://user-images.githubusercontent.com/38847486/219843298-5a1f5a86-7073-4dd8-8388-91201b9c1077.png)
（EOE团队指露早gogo，虞莫momo，柚恩不加糖，莞儿睡不醒，米诺高分少女，EOE组合）
暂未发现其他无法订阅的账号。

群友的相同插件的bot也无法订阅，其他类型的bot可以成功订阅上述账号

**Comment by guohuiyuan** [comment]
管人痴

**Comment by guohuiyuan** [comment]
后面我请求加个cookie

**Comment by guohuiyuan** [comment]
#599 修复了
