### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Lycofuture** [FloatTech/ZeroBot-Plugin#628]
一直启动不了，系统都重装了一遍还是启动失败
版本:1.7.0bate5
![Screenshot_20230318-221722_Termux](https://user-images.githubusercontent.com/77215384/226111641-fbfa4f1c-5f47-4192-b494-3e4ae1130c8c.png)

**Comment by fumiama** [comment]
你，，，网不好😂

**Comment by Lycofuture** [comment]
> 

只支持国内源，不支持国外源吗？？？

**Comment by fumiama** [comment]
啊这，你要是实在下不下来，就去 https://github.com/FloatTech/zbpdata 下载所有文件，放到 ~/data 下。
