### ISSUE TITLE
加载失败，什么签也没有哦~

### ISSUE THREAD

**Issue by Cattailglows** [FloatTech/ZeroBot-Plugin#652]
![
![%1(P UM ALZR XTI{)%PUQH](https://user-images.githubusercontent.com/127735632/229472041-1aa23d2f-8147-431f-b962-3761f9234b8c.png)
HLC$POGSQ(PPP_`3WC NMIX](https://user-images.githubusercontent.com/127735632/229468802-406318c3-5e96-4cc0-9330-37f912ffc454.png)
bot能用，应该不是网络问题吧。

**Comment by Cattailglows** [comment]
![%1(P UM ALZR XTI{)%PUQH](https://user-images.githubusercontent.com/127735632/229472186-6f7b16d2-9a13-48fe-958c-fdf6d79d66ee.png)

**Comment by fumiama** [comment]
我不认为这是能用的状态（

**Comment by Cattailglows** [comment]
> 我不认为这是能用的状态（

可是QQ上跟他说话，他会回复我诶。所以说还是梯子的问题嘛。

**Comment by lianhong2758** [comment]
> > 我不认为这是能用的状态（
> 
> 可是QQ上跟他说话，他会回复我诶。所以说还是梯子的问题嘛。

我认为这不是能用的状态

**Comment by weigui404** [comment]
> 

我认为，他会说话和zbp没有关系。
