### ISSUE TITLE
猜歌插件下载歌单失败

### ISSUE THREAD

**Issue by rednoon** [FloatTech/ZeroBot-Plugin#670]
[guessmusic]error:Get "playlist/track/all?id=（歌单id）": unsupported protocol scheme ""
是不是代码里地址不对。下载歌单的链接是https://music.163.com/#/playlist?id=（歌单id）

**Comment by fumiama** [comment]
@fangliuyu

**Comment by fangliuyu** [comment]
@rednoon 请确认你是否已经使用"设置猜歌API"指令设置了NeteaseCloudMusicApi框架的API?

**Comment by guohuiyuan** [comment]
红月老师，爬

**Comment by rednoon** [comment]
好了。另外好像”我喜欢的歌曲“这个歌单是不能读取的，不知道是api的问题还是网易云那边的问题
