### ISSUE TITLE
WebSocket 服务器 收不到任何消息

### ISSUE THREAD

**Issue by TimeRainStarSky** [FloatTech/ZeroBot-Plugin#680]
![1](https://user-images.githubusercontent.com/63490117/234157616-d0b15ab0-0027-4e0f-a233-a42b31343133.jpg)
go-cqhttp 正常收消息，且连接的其他端（NoneBot）也能正常收到消息

**Comment by fumiama** [comment]
试试最新。

**Comment by Mubanjun** [comment]
服务器配置可能有误。
- zbp使用的为***正向ws***，请检查配置文件，如果有误请参考[go-cqhttp文档](https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF)改正。
- 如果和NoneBot共用服务器，请阅读go-cqhttp文档为zbp再建一个正向ws服务器，如果仍然不行可尝试配置gocqhttp的config.yml，服务器映射设成回环地址127.0.0.1或localhost
- 若手机正在同时运行V2rayNG或Clash等类似工具，请配置设置绕过局域网地址，或绕过Termux应用
- 若正在使用Tmoe Ubuntu 18 LTS，请打开天萌卸载后更新系统
