### ISSUE TITLE
BUG-1.7.1-beta3不处理消息

### ISSUE THREAD

**Issue by 502milk** [FloatTech/ZeroBot-Plugin#681]
图一为1.7.1bete1，能够正常响应
![1](https://user-images.githubusercontent.com/49502047/234573588-759ed379-7cd8-4961-ba86-0b92a1ce2190.jpg)
图二为1.7.1bete3，无法响应消息内容
![2](https://user-images.githubusercontent.com/49502047/234573714-756f79f7-0c64-43a1-8e48-ccc1938b5fc2.jpg)

平台win11
使用版本1.7.1-bete3 amd64

**Comment by Jiang-Red** [comment]
新版逻辑改变，插件控制部分需要艾特bot

**Comment by 502milk** [comment]
阿这。。。~~彳亍吧~~
