### ISSUE TITLE
漂流瓶功能优化

### ISSUE THREAD

**Issue by rednoon** [FloatTech/ZeroBot-Plugin#688]
漂流瓶捞起之后感觉应该把那条消息在数据库中删除比较好，现在是不会删除

另外希望加一个跨群/不跨群的开关。

这两个实现应该不难吧。第一个加一行删除，第二个加一个判断当前群组id比较

**Comment by Jiang-Red** [comment]
之前的版本就是删除和不跨群，现在好了，又要改回去了

**Comment by rednoon** [comment]
啊这😥

**Comment by MoYoez** [comment]
是这样的 你可以找一下1.62版之前的 可以满足要求
