### ISSUE TITLE
百度内容审核配置无反应

### ISSUE THREAD

**Issue by lingyunytc** [FloatTech/ZeroBot-Plugin#692]
其它指令是正常的
在群内发送“获取BDAKey”或艾特机器人发送均无反应
在私聊发送“获取BDAKey”或”/获取BDAKey“发送均无反应
配置BDAKey指令同样

**Comment by lingyunytc** [comment]
> 请确保你拥有主人权限

已在config.json文件中的super_users后填写自己的qq号，群内发送/响应等命令有反应

**Comment by Jiang-Red** [comment]
你确定吗，你有使用zbp -c config.json启动吗？我这里是正常的
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/79574799/b09d125c-f29c-4904-9200-53a9e01b0a22)

**Comment by lingyunytc** [comment]
> 你确定吗，你有使用zbp -c config.json启动吗？我这里是正常的 ![图像](https://user-images.githubusercontent.com/79574799/244913036-b09d125c-f29c-4904-9200-53a9e01b0a22.png)

感谢，已正常，不能用记事本编辑config.json
