### ISSUE TITLE
图片与语音无法正常发送，目测为CQ码不规范

### ISSUE THREAD

**Issue by Mubanjun** [FloatTech/ZeroBot-Plugin#707]
如图所示，我们还特意试了试，不是网络不可达就是CQ码无效，但是！这些网址是可以使用同一台设备同一个网络同一个环境打开***正常播放***的！
![2faf7cad3e206298](https://github.com/FloatTech/ZeroBot-Plugin/assets/110292675/57497060-8338-4e73-9386-6c0dbd66a79a)
**系统**:Ubuntu 20.04 LTS
已安装最新版ffmpeg，所有系统组件均为最新，go-cqhttp是用的是最新版
*萝卜子嘲讽的语音倒是可以发出来*

**Comment by fumiama** [comment]
和CQ码无关，就是你DNS问题。建议先禁用下ipv6 dns优先用ipv4试试。至于为什么显示CQ码，是因为go-cqhttp发现对应文件根本不是mp3，没法解析发送，所以按CQ码发出了。

**Comment by Mubanjun** [comment]
我这没有IPv6，只有IPv4

**Comment by fumiama** [comment]
是啊，所以很明显是你DNS问题，误给你解析了ipv6地址导致无法访问。

**Comment by Mubanjun** [comment]
都不行，加密DNS已经关了
附件:[Image]

[Image]


访问我的主页！在https://b23.tv/5W9VC6
________________________________

**Comment by fumiama** [comment]
你图没发出来。另外，如果你确信DNS没问题，那可以怀疑一下你搭建的平台。你是在哪里运行的zbp？

**Comment by Mubanjun** [comment]
> 你图没发出来。另外，如果你确信DNS没问题，那可以怀疑一下你搭建的平台。你是在哪里运行的zbp？

使用Termux-proot容器安装的Ubuntu20.04LTS，所有包已更至最新，原来也是这么搭建的，一点问题没有，这次就直接换的zbp目录里的所有文件，按理说不应该有问题啊

**Comment by fumiama** [comment]
termux确实会有网络问题。我忘了怎么解决的了，好像是改resolv.conf或者按GOOS=android编译？你可以查查。

**Comment by Mubanjun** [comment]
![16905202610018998053927432348197](https://github.com/FloatTech/ZeroBot-Plugin/assets/110292675/8f13ec8d-c3e7-4692-9f19-5479599619ab)
![16905204126556018040634631197969](https://github.com/FloatTech/ZeroBot-Plugin/assets/110292675/791e5cb6-ec05-4976-9003-60ef79c82594)
![16905204449065047044080621164251](https://github.com/FloatTech/ZeroBot-Plugin/assets/110292675/5a001be3-85d1-4d64-879a-36804e2ba071)

**Comment by Mubanjun** [comment]
> 

我记得原来改过一回，并且[天萌](https://github.com/2moe/tmoe) 默认就会帮忙改动网络配置，按理说不应该🤔

**Comment by fumiama** [comment]
频道啊，go-cqhttp对频道支持基本残废，一切以群聊为准😂
