### ISSUE TITLE
如何设置openai.api_base

### ISSUE THREAD

**Issue by homo11451419** [FloatTech/ZeroBot-Plugin#718]
在使用机器人的过程中，我发现该机器人可以设置openai的gpt3.5，但是由于没钱(白嫖api)，所以想要设置openai.api_base，但是找遍了仓库也没找到方法，我要设置的openai.api_base是"https://api.openai.com/v1/completions"，有人可以解决吗，谢谢

**Comment by Jiang-Red** [comment]
aireply插件的gpt目前无法使用，如有需要可看 [zbppg](https://github.com/FloatTech/ZeroBot-Plugin-Playground)
