### ISSUE TITLE
群管部分指令不能用

### ISSUE THREAD

**Issue by chenanmo** [FloatTech/ZeroBot-Plugin#72]
使用的时候发现，解除禁言指令，设置取消管理指令不能够使用，是还需要配置什么吗？
已经设置主人QQ，只启用了群管。

**Comment by fumiama** [comment]
经测试群管插件没有问题，可能是你使用的`onebot`不支持这些接口。建议升级你使用的框架或改为使用[go-cqhttp](https://github.com/Mrs4s/go-cqhttp)
