### ISSUE TITLE
关于全局启用/禁用功能

### ISSUE THREAD

**Issue by DefFrancis** [FloatTech/ZeroBot-Plugin#728]
似乎设置了某个功能全局启用/禁用以后，在单个群里单独启用/禁用这个功能会失效，总是遵循全局的状态。
如何关闭设置过的某个功能的全局启用/禁用状态呢？

**Comment by fumiama** [comment]
那就不是全局了

**Comment by fumiama** [comment]
你可能在找：更改默认启用状态

**Comment by DefFrancis** [comment]
> 你可能在找：更改默认启用状态

可能我的描述不够清楚。QAQ
举个例子:
首先我在A群:
A群：@bot /全局启用 atri
bot:已全局启用服务: atri
@bot /服务列表
atri服务是开启的

此时转到B群:
B群：@bot /禁用 atri
bot:已禁用服务: atri
@bot /服务列表
此时b群的atri服务仍然存在

我想了解的是如何取消（A群）设置过的全局启用，解除对b群的影响

**Comment by Jiang-Red** [comment]
用`/还原 xxx`

**Comment by DefFrancis** [comment]
> 用`/还原 xxx`

![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/32185830/a9541580-f82d-4d49-9471-09b0b08e548c)

**Comment by DefFrancis** [comment]
难道是bug?

**Comment by fumiama** [comment]
> 你可能在找：更改默认启用状态

如上。

**Comment by DefFrancis** [comment]
直接删除了data\control\plugins.db以达到重置的目的了（）
