### ISSUE TITLE
钓鱼系统超卖，1件物品多次出售

### ISSUE THREAD

**Issue by bincooo** [FloatTech/ZeroBot-Plugin#756]
玩家通过快速发送出售多条相同的出售命令达到一件物品多次出售的情况，我用限流器暂时解决了。望修复！
价格似乎也挺离谱的，来钱太快了...  
<img width="779" alt="截屏2023-09-22 14 11 25" src="https://github.com/FloatTech/ZeroBot-Plugin/assets/36452456/b78b2477-79dc-4d43-a3ca-712c2a8c55ee">

**Comment by fumiama** [comment]
@fangliuyu

**Comment by fangliuyu** [comment]
@bincooo 
1.反并发函数目前不能反瞬间相同的信息，目前我不知道如何修
2.价格可在“data/mcfish/articlesInfo.json"中进行修改

**Comment by bincooo** [comment]
> @bincooo 1.反并发函数目前不能反瞬间相同的信息，目前我不知道如何修 2.价格可在“data/mcfish/articlesInfo.json"中进行修改

谢回。

我提一下思路吧，我临时解决的。
1.自定义限流器，每个玩家3秒1次。（会漏，原因不明）
2.用户锁，每个玩家分配一把锁。
1+2 目前好像没啥问题，不知道有没有遗漏的 (˶‾᷄ ⁻̫ ‾᷅˵)
