### ISSUE TITLE
签到问题

### ISSUE THREAD

**Issue by Jerry-top** [FloatTech/ZeroBot-Plugin#779]
execute handler err: runtime error: invalid memory address or nil pointer dereference
goroutine 1008 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/wdvxdr1123/ZeroBot.match.func2.1.1()
        github.com/wdvxdr1123/ZeroBot@v1.7.4/bot.go:253 +0x45
panic({0xf773c0, 0x19f4700})
        runtime/panic.go:884 +0x213
github.com/jinzhu/gorm.(*DB).clone(0x0)
        github.com/jinzhu/gorm@v1.9.16/main.go:853 +0x1d
github.com/jinzhu/gorm.(*DB).Model(...)
        github.com/jinzhu/gorm@v1.9.16/main.go:513
github.com/FloatTech/ZeroBot-Plugin/plugin/score.(*scoredb).GetSignInByUID(0xc00099b830?, 0xc0009c4198?)
        github.com/FloatTech/ZeroBot-Plugin/plugin/score/model.go:95 +0x4e
github.com/FloatTech/ZeroBot-Plugin/plugin/score.init.0.func2(0xc000b0bae0)
        github.com/FloatTech/ZeroBot-Plugin/plugin/score/sign_in.go:102 +0x265
github.com/wdvxdr1123/ZeroBot.match.func2.1()
        github.com/wdvxdr1123/ZeroBot@v1.7.4/bot.go:256 +0x68
created by github.com/wdvxdr1123/ZeroBot.match.func2
        github.com/wdvxdr1123/ZeroBot@v1.7.4/bot.go:249 +0xaa

**Comment by 45610465** [comment]
我也遇到了这个问题
