### ISSUE TITLE
ARTI词库无法启用

### ISSUE THREAD

**Issue by Stardust-minus** [FloatTech/ZeroBot-Plugin#81]
![7UNA 7BCEX}P1$5ZXO2OLK2](https://user-images.githubusercontent.com/52093397/143598754-398937a8-97e0-4eec-82f6-5681365faf61.png)
![image](https://user-images.githubusercontent.com/52093397/143598889-43ecd829-cff2-47c3-b3c6-11140027201b.png)
![image](https://user-images.githubusercontent.com/52093397/143598967-14805a7b-00d6-4077-8381-84c0116bc103.png)

如图。系统为Centos7.9，使用go run和go build均无法启用该词库回复.

**Comment by fumiama** [comment]
请参照以下方法提供更详细截图，尝试是否可以解决问题
- 确保程序为最新版本
- 在群中输入 /服务列表 查看 atri 插件启用状态

**Comment by Stardust-minus** [comment]
服务列表里依然没有ARTI，但是现在莫名其妙的能用了
更莫名其妙的事，vup查询什么的又炸掉了
回头尝试一下在线Action，感觉是编译问题？
