### ISSUE TITLE
能否考虑增加一个整体全局限速模式

### ISSUE THREAD

**Issue by byx2020** [FloatTech/ZeroBot-Plugin#818]
标题可能有点误导性，我知道zbp目前是已经有了一个全局限速的，
但是目前的全局限速让每个插件使用的都是单独的缓存区，
即，当我设置了每30秒触发1次消息之后，然后触发1次A插件，A插件在之后30秒内确实是无法被再次触发了，但仍然可以触发B插件或C插件等等，
而我希望的效果是，触发1次A插件之后30秒内，不管是B插件还是C插件，均无法被触发，也就是所有插件共用一个缓存区，
说起来可能有点绕，其实就是我希望zbp能够有一个整体的限速，这个限速不会因为插件的不同而改变，
其实这个改起来应该也不麻烦，增加一个模式，在限速时让所有插件共用同一个插件ID就行，
本来我是想自己直接改的的，但我水平有限，没找到限速标识相关的代码，所以只好麻烦一下大佬了，非常感谢。

**Comment by Jiang-Red** [comment]
aifalse 插件中有

**Comment by fumiama** [comment]
调大`-l`参数，即可达到你的效果。注意这会大大延长事件响应时间，如果你群多的话。

**Comment by byx2020** [comment]
> 调大`-l`参数，即可达到你的效果。注意这会大大延长事件响应时间，如果你群多的话。

先感谢大佬能够抽时间解答，不过刚刚我去看了一下`-l`参数，发现这是这个参数是用于延时的，
大佬你可能误解我的意思了，因为我需要的不是“延时处理”，而是“忽略指令”或者“不处理”，
之所以会提出这个需求，是因为有部分群友喜欢每天一上来就“每日运势”“群老婆”“塔罗牌”“浅草百签”四连(都是不同插件的指令)，这会让机器人在短时间内连续回复四次，可能会增加风控概率，
以前这样倒是无所谓，但是最近我机器人被封号了好几次，已经在使用并不稳定的8.9.83版本签名服务了，目前差不多是发言一次就会校验一次，很容易就出问题，
所以我希望能够给机器人使用更加保守一些的发言策略，比如就在上面几个指令里面，让群友每天在一小时内只能用其中一个指令就行了，主要是想避免一下子连续用多个指令导致短时间内多次回复的情况。

**Comment by guohuiyuan** [comment]
> > 调大`-l`参数，即可达到你的效果。注意这会大大延长事件响应时间，如果你群多的话。
> 
> 先感谢大佬能够抽时间解答，不过刚刚我去看了一下`-l`参数，发现这是这个参数是用于延时的， 大佬你可能误解我的意思了，因为我需要的不是“延时处理”，而是“忽略指令”或者“不处理”， 之所以会提出这个需求，是因为有部分群友喜欢每天一上来就“每日运势”“群老婆”“塔罗牌”“浅草百签”四连(都是不同插件的指令)，这会让机器人在短时间内连续回复四次，可能会增加风控概率， 以前这样倒是无所谓，但是最近我机器人被封号了好几次，已经在使用并不稳定的8.9.83版本签名服务了，目前差不多是发言一次就会校验一次，很容易就出问题， 所以我希望能够给机器人使用更加保守一些的发言策略，比如就在上面几个指令里面，让群友每天在一小时内只能用其中一个指令就行了，主要是想避免一下子连续用多个指令导致短时间内多次回复的情况。

换llonebot

**Comment by fumiama** [comment]
正确的。

**Comment by byx2020** [comment]
> 换llonebot

@guohuiyuan 感谢提醒，我已经用了llonebot一段时间了，哎，
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/58938653/71852a16-868a-4ea4-b061-62600a99d18b)
