### ISSUE TITLE
来份萝莉功能无法使用

### ISSUE THREAD

**Issue by Myzhazha** [FloatTech/ZeroBot-Plugin#82]
控制台返回
`INFO[5054] 收到私聊消息 哦豁 : 来份萝莉                             
ERRO[5055] 调用 API: send_group_msg 时出现错误, RetCode: 100, Msg: GROUP_NOT_FOUND, Wording: 群聊不存在 
ERRO[5056] 调用 API: send_group_msg 时出现错误, RetCode: 100, Msg: GROUP_NOT_FOUND, Wording: 群聊不存在 
ERRO[5084] 调用 API: send_private_msg 时出现错误: timed out`

**Comment by fumiama** [comment]
这是正常现象，该插件会向不存在的群号`0`发送图片进行缓存，等待图片加载完毕，即向群发送图片。

**Comment by jx9468** [comment]
> 这是正常现象，该插件会向不存在的群号发送图片进行缓存，等待图片加载完毕，即向群发送图片。`0`

请问一下使用go—cqhttp运行的vtb功能报错，什么转换失败，这个是什么原因。有解决办法吗

Zerobot返回 ：level=error msg="调用 API: send_group_msg 时出现错误, RetCode: 100, Msg: SEND_MSG_API_ERROR, Wording: 请参考 go-cqhttp 端输出"

go—cqhttp返回：转换CQ码 ({"type":"record","data":{"file":"https://vtbkeyboard.moe/api/audio/672328094/%E6%89%8B%E6%8A%96%E7%9A%84%E5%8E%89%E5%AE%B3.mp3"}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码.
[WARNING]: 群消息发送失败: 消息为空.

**Comment by Myzhazha** [comment]
> > 这是正常现象，该插件会向不显示的群号发送图片进行出现，等待图片加载完毕，即向群发送图片。`0`
> 
> 好像一下使用go—cqhttp运行的vtb功能报错，什么转换失败，这是什么原因。有解决办法吗？
> 
> Zerobot返回 ：level=error msg="调用 API: send_group_msg 时出现错误, RetCode: 100, Msg: SEND_MSG_API_ERROR, Wording: 请参考 go-cqhttp 端输出"
> 
> go—cqhttp返回：转换CQ码({"type":"record","data":{"file":" [https://vtbkeyboard.moe/api/audio/672328094/%E6%89%8B%E6 %8A%96%E7%9A%84%E5%8E%89%E5%AE%B3.mp3"}}](https://vtbkeyboard.moe/api/audio/672328094/%E6%89%8B%E6%8A%96%E7%9A%84%E5%8E%89%E5%AE%B3.mp3%22%7D%7D) ) 到MiraiGo Element时出现错误：encode Silk failed: convert pcm file error: exec: "ffmpeg":在 %PATH% 中找不到可执行文件将忽略本段CQ 码。 [WARNING]: 群消息发送失败：消息为空。

go-cqhttp的文档里有教程，安装FFmpeg并配置环境变量

**Comment by guohuiyuan** [comment]
> > 这是正常现象，该插件会向不存在的群号发送图片进行缓存，等待图片加载完毕，即向群发送图片。`0`
> 
> 请问一下使用go—cqhttp运行的vtb功能报错，什么转换失败，这个是什么原因。有解决办法吗
> 
> Zerobot返回 ：level=error msg="调用 API: send_group_msg 时出现错误, RetCode: 100, Msg: SEND_MSG_API_ERROR, Wording: 请参考 go-cqhttp 端输出"
> 
> go—cqhttp返回：转换CQ码 ({"type":"record","data":{"file":"[https://vtbkeyboard.moe/api/audio/672328094/%E6%89%8B%E6%8A%96%E7%9A%84%E5%8E%89%E5%AE%B3.mp3"}}](https://vtbkeyboard.moe/api/audio/672328094/%E6%89%8B%E6%8A%96%E7%9A%84%E5%8E%89%E5%AE%B3.mp3%22%7D%7D)) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码. [WARNING]: 群消息发送失败: 消息为空.

下载了ffmpeg吗
