### ISSUE TITLE
ERROR: 风控校验失败

### ISSUE THREAD

**Issue by Natane0808** [FloatTech/ZeroBot-Plugin#899]
1. 添加b站订阅时报错，频率较高
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/48778330/4eee27f8-e03c-4f21-8f1f-1c01a77c1238)
2. 拉取b站推送会报403
![image](https://github.com/FloatTech/ZeroBot-Plugin/assets/48778330/0d3772e7-7a23-4c11-b229-4579fbeb4bf9)

**Comment by guohuiyuan** [comment]
cookie要给全的。从浏览器复制下来
