### ISSUE TITLE
webui需要改main.go吗？

### ISSUE THREAD

**Issue by AndoKaguya** [FloatTech/ZeroBot-Plugin#910]
请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？

**Comment by thatstarryflow** [comment]
需要改三处，详见我的博客。
http://blog.oops.cyou/index.php/archives/26/

**Comment by thatstarryflow** [comment]
> 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
需要改三处，详见我的博客。
http://blog.oops.cyou/index.php/archives/26/

**Comment by AndoKaguya** [comment]
> > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > 需要改三处，详见我的博客。
> > http://blog.oops.cyou/index.php/archives/26/

谢谢！

**Comment by AndoKaguya** [comment]
> > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > 需要改三处，详见我的博客。
> > http://blog.oops.cyou/index.php/archives/26/

呜呜呜，大佬，修改了三处之后，GitHub那里actions还是编译错误

**Comment by thatstarryflow** [comment]
> > > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > > 需要改三处，详见我的博客。
> > > http://blog.oops.cyou/index.php/archives/26/
> 
> 呜呜呜，大佬，修改了三处之后，GitHub那里actions还是编译错误

Actions我没用过哎，我直接跑是正常的，可以尝试git下来再编译。

**Comment by thatstarryflow** [comment]
> > > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > > 需要改三处，详见我的博客。
> > > http://blog.oops.cyou/index.php/archives/26/
> 
> 呜呜呜，大佬，修改了三处之后，GitHub那里actions还是编译错误
能具体说说报了哪些错误吗

**Comment by AndoKaguya** [comment]
> > > > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > > > 需要改三处，详见我的博客。
> > > > http://blog.oops.cyou/index.php/archives/26/
> > 
> > 
> > 呜呜呜，大佬，修改了三处之后，GitHub那里actions还是编译错误
> > 能具体说说报了哪些错误吗

不是很理解这种是什么错误
![QQ截图20240520130424](https://github.com/FloatTech/ZeroBot-Plugin/assets/53990829/2fe75563-c7bb-4d94-9d15-f6e74549f867)
![QQ截图20240520130509](https://github.com/FloatTech/ZeroBot-Plugin/assets/53990829/a6e0bd95-32c3-4e36-b8e1-63fe64f3d8b8)

**Comment by thatstarryflow** [comment]
> > > > > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > > > > 需要改三处，详见我的博客。
> > > > > http://blog.oops.cyou/index.php/archives/26/
> > > 
> > > 
> > > 呜呜呜，大佬，修改了三处之后，GitHub那里actions还是编译错误
> > > 能具体说说报了哪些错误吗
> 
> 不是很理解这种是什么错误 ![QQ截图20240520130424](https://private-user-images.githubusercontent.com/53990829/331948929-2fe75563-c7bb-4d94-9d15-f6e74549f867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODYyNjMsIm5iZiI6MTcxNjE4NTk2MywicGF0aCI6Ii81Mzk5MDgyOS8zMzE5NDg5MjktMmZlNzU1NjMtYzdiYi00ZDk0LTlkMTUtZjZlNzQ1NDlmODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZGVkMjIyODc4YTEzNDZmM2NjMGQ4OTg2ODM4MDBhMWQyYWYyNzQ4ZDVkMmZkMjMzZTE1ZDc2MTliYTA3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YsKOx74pp8EoGHIPRHn0eTBG-c18ZCEc1jojA7gBj1s) ![QQ截图20240520130509](https://private-user-images.githubusercontent.com/53990829/331948942-a6e0bd95-32c3-4e36-b8e1-63fe64f3d8b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODYyNjMsIm5iZiI6MTcxNjE4NTk2MywicGF0aCI6Ii81Mzk5MDgyOS8zMzE5NDg5NDItYTZlMGJkOTUtMzJjMy00ZTM2LWI4ZTEtNjNmZTY0ZjNkOGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOGY2Njc2YjBjOWEzZGU4NWFkODVhMmU2NGZiYmEwOWFjY2FhNTg0ZGEwNTI2MzU4ZjM4YzIzYmMzYmYwN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCWkOR_ecrOw-p1HrjtJsDfmuLBN_mikMxrQi1n-hm4)

不是很清楚，可以尝试git下来编译，我这里本地编译是没有问题的
![图片](https://github.com/FloatTech/ZeroBot-Plugin/assets/88170243/c036f28a-1de0-4f20-a86d-6034954d6da9)

**Comment by AndoKaguya** [comment]
> > > > > > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > > > > > 需要改三处，详见我的博客。
> > > > > > http://blog.oops.cyou/index.php/archives/26/
> > > > 
> > > > 
> > > > 呜呜呜，大佬，修改了三处之后，GitHub那里actions还是编译错误
> > > > 能具体说说报了哪些错误吗
> > 
> > 
> > 不是很理解这种是什么错误 ![QQ截图20240520130424](https://private-user-images.githubusercontent.com/53990829/331948929-2fe75563-c7bb-4d94-9d15-f6e74549f867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODYyNjMsIm5iZiI6MTcxNjE4NTk2MywicGF0aCI6Ii81Mzk5MDgyOS8zMzE5NDg5MjktMmZlNzU1NjMtYzdiYi00ZDk0LTlkMTUtZjZlNzQ1NDlmODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZGVkMjIyODc4YTEzNDZmM2NjMGQ4OTg2ODM4MDBhMWQyYWYyNzQ4ZDVkMmZkMjMzZTE1ZDc2MTliYTA3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YsKOx74pp8EoGHIPRHn0eTBG-c18ZCEc1jojA7gBj1s) ![QQ截图20240520130509](https://private-user-images.githubusercontent.com/53990829/331948942-a6e0bd95-32c3-4e36-b8e1-63fe64f3d8b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODYyNjMsIm5iZiI6MTcxNjE4NTk2MywicGF0aCI6Ii81Mzk5MDgyOS8zMzE5NDg5NDItYTZlMGJkOTUtMzJjMy00ZTM2LWI4ZTEtNjNmZTY0ZjNkOGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOGY2Njc2YjBjOWEzZGU4NWFkODVhMmU2NGZiYmEwOWFjY2FhNTg0ZGEwNTI2MzU4ZjM4YzIzYmMzYmYwN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCWkOR_ecrOw-p1HrjtJsDfmuLBN_mikMxrQi1n-hm4)
> 
> 不是很清楚，可以尝试git下来编译，我这里本地编译是没有问题的 ![图片](https://private-user-images.githubusercontent.com/88170243/331963089-c036f28a-1de0-4f20-a86d-6034954d6da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDc3MTMsIm5iZiI6MTcxNjIwNzQxMywicGF0aCI6Ii84ODE3MDI0My8zMzE5NjMwODktYzAzNmYyOGEtMWRlMC00ZjIwLWE4NmQtNjAzNDk1NGQ2ZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEyMTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNTFhOTRkYWQ4YzYzMGM3Mzg2MThhZGQ1MmI5YmQzMTFhZDdjYTllOWExNDhjOWIwNDAzMTc5NDkzOTI4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MfL0gohUETNvqiLL4w6V-Fgf-KeH8toAVLKuJTfqAAQ)

好的，谢谢，我尝试一下

**Comment by qingtian-crazy** [comment]
> > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > 需要改三处，详见我的博客。
> > http://blog.oops.cyou/index.php/archives/26/
你好我也想启用一下webui，但是您的博客我无法访问

**Comment by qingtian-crazy** [comment]
> > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > 需要改三处，详见我的博客。
> > http://blog.oops.cyou/index.php/archives/26/
你好我也想启用一下webui，但是您的博客我无法访问

**Comment by qingtian-crazy** [comment]
> > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > 需要改三处，详见我的博客。
> > http://blog.oops.cyou/index.php/archives/26/

你好我也想启用一下webui，但是您的博客我无法访问

**Comment by thatstarryflow** [comment]
> > > 请问启用webui需要修改main.go文件吗，修改了两处和web相关，但是编译失败呢，是否不用修改，直接机器人命令启动呢？
> > > 需要改三处，详见我的博客。
> > > http://blog.oops.cyou/index.php/archives/26/
> 
> 你好我也想启用一下webui，但是您的博客我无法访问

![2bc5b0fa6a44100f2758d7024116866](https://github.com/user-attachments/assets/736b5176-392e-4801-b143-27990cc79d1a)
![b994f078659e59a0cb76886de7ac412](https://github.com/user-attachments/assets/db6ee7ba-120c-4993-a31d-86da75fd36b9)
![affbcc7cac0eb87ec79424ad5fbadc8](https://github.com/user-attachments/assets/5b5a2d03-b850-45a5-b73a-6991cc29f9c3)
需要取消这三行代码的注释
