### ISSUE TITLE
[score]签到功能获取钱包余额错误

### ISSUE THREAD

**Issue by vatebur** [FloatTech/ZeroBot-Plugin#978]
- 现象：生成的签到图片，钱包余额为零
- 原因：怀疑是应为调用 `wallet.InsertWalletOf` 的时候使用了异步执行，锁表了。导致  `wallet.GetWalletOf(uid)` 因为表被锁了执行异常。
- 版本： [API修改](https://github.com/FloatTech/AnimeAPI/commit/ab2213881e0137d614b0f193e157c39b0b6e9838) 
可能是因为改提交给api加了锁导致了这个问题。
- 解决办法：1.直接去掉异步执行 2.是否有必要对API进行修改？

plugin/score/sign_in.go:142
```go
		go func() {
			err = wallet.InsertWalletOf(uid, add)
			if err != nil {
				ctx.SendChain(message.Text("ERROR: ", err))
				return
			}
		}()
		alldata := &scdata{
			drawedfile: drawedFile,
			picfile:    picFile,
			uid:        uid,
			nickname:   ctx.CardOrNickName(uid),
			inc:        add,
			score:      wallet.GetWalletOf(uid),
			level:      level,
			rank:       rank,
		}
```

**Comment by fumiama** [comment]
现在的sqlite实现较为原始，后续考虑彻底升级到gorm。
