### ISSUE TITLE
塔罗牌功能似乎出错了

### ISSUE THREAD

**Issue by linanf** [FloatTech/ZeroBot-Plugin#990]
使用塔罗牌功能无法发送图片，查看了https://gitcode.net/shudorcl/zbp-tarot/也无法访问
![Image_1727772567304](https://github.com/user-attachments/assets/5e4de1fc-55c7-4009-b86a-f90599a16c9a)
![Image_1727772836606](https://github.com/user-attachments/assets/b1280236-76e2-4934-a6df-0409bc15e398)

**Comment by fumiama** [comment]
@shudorcl

**Comment by shudorcl** [comment]
gitcode无法直接访问资源了，考虑以后迁移到zbpdata
