### ISSUE TITLE
aifalse库中检查身体的新浪图床失效了，添加rerfer方法不行

### ISSUE THREAD

**Issue by shuiyuekotomi** [FloatTech/ZeroBot-Plugin#997]
这几天一只dial tcp失败，提示403，自己换了图床之后，却不能做到随机图片
ERROR: Head "https://iw233.cn/api.php?sort=mp": read tcp 192.168.99.17:53013->121.62.20.208:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by fumiama** [comment]
无法复现。

**Comment by lianhong2758** [comment]
感觉是你DNS出错了,一般服务器需要自己改一下的,这家图片API一直没出问题

**Comment by vatebur** [comment]
已更换api #1077
